-- Heavy 
INSERT INTO ArtDefine_UnitMemberCombatWeapons	(UnitMemberType,							"Index", SubIndex, ID,   VisKillStrengthMin, VisKillStrengthMax,   ProjectileSpeed, ProjectileTurnRateMin,	ProjectileTurnRateMax,	HitEffect,													HitEffectScale, HitRadius, ProjectileChildEffectScale, AreaDamageDelay, ContinuousFire, WaitForEffectCompletion, TargetGround, IsDropped, WeaponTypeTag,	WeaponTypeSoundOverrideTag)
VALUES											('ART_DEF_UNIT_MEMBER_IG_HEAVY',			0,		 0,				 null, 1.0,          1.0,				   null,			null,				    null,					'ART_DEF_VEFFECT_FIGHTER_MACHINE_GUN_HIT_$(TERRAIN)',		0.2,			15,		   null,					   null,			1,				null,					 null,		   null,	  'BULLETHC',		'BULLETHC');
-- Sergeant
INSERT INTO ArtDefine_UnitMemberCombatWeapons	(UnitMemberType,							"Index", SubIndex, ID,   VisKillStrengthMin, VisKillStrengthMax,   ProjectileSpeed, ProjectileTurnRateMin,	ProjectileTurnRateMax,	HitEffect,													HitEffectScale, HitRadius, ProjectileChildEffectScale, AreaDamageDelay, ContinuousFire, WaitForEffectCompletion, TargetGround, IsDropped, WeaponTypeTag,	WeaponTypeSoundOverrideTag)
VALUES											('ART_DEF_UNIT_MEMBER_IG_SGT',				0,	     0,        null, null,               null,				   null,			null,					null,					null,														null,			null,	   null,					   null,			null,			null,					 null,		   null,	  'BLUNT',			'BLUNT');
INSERT INTO ArtDefine_UnitMemberCombatWeapons	(UnitMemberType,							"Index", SubIndex, ID,   VisKillStrengthMin, VisKillStrengthMax,   ProjectileSpeed, ProjectileTurnRateMin,	ProjectileTurnRateMax,	HitEffect,													HitEffectScale, HitRadius, ProjectileChildEffectScale, AreaDamageDelay, ContinuousFire, WaitForEffectCompletion, TargetGround, IsDropped, WeaponTypeTag,	WeaponTypeSoundOverrideTag)
VALUES											('ART_DEF_UNIT_MEMBER_IG_SGT',				1,	     0,        null, 10,                 20,				   null,			null,					null,					null,														null,			null,	   null,					   null,			null,			null,					 null,		   null,	  'FLAMING_ARROW',	null				);
-- Soldier
INSERT INTO ArtDefine_UnitMemberCombatWeapons	(UnitMemberType,							"Index", SubIndex, ID,   VisKillStrengthMin, VisKillStrengthMax,   ProjectileSpeed, ProjectileTurnRateMin,	ProjectileTurnRateMax,	HitEffect,													HitEffectScale, HitRadius, ProjectileChildEffectScale, AreaDamageDelay, ContinuousFire, WaitForEffectCompletion, TargetGround, IsDropped, WeaponTypeTag,	WeaponTypeSoundOverrideTag)
VALUES											('ART_DEF_UNIT_MEMBER_IG_SOLDIER',			0,	     0,        null, null,               null,				   null,			null,					null,					null,														null,			null,	   null,					   null,			null,			null,					 null,		   null,	  'BULLET',			'BULLET');
-- Trooper
INSERT INTO ArtDefine_UnitMemberCombatWeapons	(UnitMemberType,							"Index", SubIndex, ID,   VisKillStrengthMin, VisKillStrengthMax,   ProjectileSpeed, ProjectileTurnRateMin,	ProjectileTurnRateMax,	HitEffect,													HitEffectScale, HitRadius, ProjectileChildEffectScale, AreaDamageDelay, ContinuousFire, WaitForEffectCompletion, TargetGround, IsDropped, WeaponTypeTag,	WeaponTypeSoundOverrideTag)
VALUES											('ART_DEF_UNIT_MEMBER_IG_TROOPER',			0,	     0,        null, null,               null,				   null,			null,					null,					null,														null,			null,	   null,					   null,			null,			null,					 null,		   null,	  'BLUNT',			'BLUNT');
INSERT INTO ArtDefine_UnitMemberCombatWeapons	(UnitMemberType,							"Index", SubIndex, ID,   VisKillStrengthMin, VisKillStrengthMax,   ProjectileSpeed, ProjectileTurnRateMin,	ProjectileTurnRateMax,	HitEffect,													HitEffectScale, HitRadius, ProjectileChildEffectScale, AreaDamageDelay, ContinuousFire, WaitForEffectCompletion, TargetGround, IsDropped, WeaponTypeTag,	WeaponTypeSoundOverrideTag)
VALUES											('ART_DEF_UNIT_MEMBER_IG_TROOPER',			1,	     0,        null, 10,                 20,				   null,			null,					null,					null,														null,			null,	   null,					   null,			null,			null,					 null,		   null,	  'FLAMING_ARROW',	null		 );
-- Vetran
INSERT INTO ArtDefine_UnitMemberCombatWeapons	(UnitMemberType,							"Index", SubIndex, ID,   VisKillStrengthMin, VisKillStrengthMax,   ProjectileSpeed, ProjectileTurnRateMin,	ProjectileTurnRateMax,	HitEffect,													HitEffectScale, HitRadius, ProjectileChildEffectScale, AreaDamageDelay, ContinuousFire, WaitForEffectCompletion, TargetGround, IsDropped, WeaponTypeTag,	WeaponTypeSoundOverrideTag)
VALUES											('ART_DEF_UNIT_MEMBER_IG_VET',				0,       0,        null, null,               null,				   null,			null,					null,					null,														null,			null,	   null,					   null,			null,			null,					 null,		   null,	  'BLUNT',			'BLUNT');
INSERT INTO ArtDefine_UnitMemberCombatWeapons	(UnitMemberType,							"Index", SubIndex, ID,   VisKillStrengthMin, VisKillStrengthMax,   ProjectileSpeed, ProjectileTurnRateMin,	ProjectileTurnRateMax,	HitEffect,													HitEffectScale, HitRadius, ProjectileChildEffectScale, AreaDamageDelay, ContinuousFire, WaitForEffectCompletion, TargetGround, IsDropped, WeaponTypeTag,	WeaponTypeSoundOverrideTag)
VALUES											('ART_DEF_UNIT_MEMBER_IG_VET',				1,       0,        null, 10,                 20,				   null,			null,					null,					null,														null,			null,	   null,					   null,			null,			null,					 null,		   null,	  'FLAMING_ARROW',	null				);
-- Chimera
INSERT INTO ArtDefine_UnitMemberCombatWeapons	(UnitMemberType,							"Index", SubIndex, ID,   VisKillStrengthMin, VisKillStrengthMax,   ProjectileSpeed, ProjectileTurnRateMin,	ProjectileTurnRateMax,	HitEffect,													HitEffectScale, HitRadius, ProjectileChildEffectScale, AreaDamageDelay, ContinuousFire, WaitForEffectCompletion, TargetGround, IsDropped, WeaponTypeTag,	WeaponTypeSoundOverrideTag)
VALUES											('ART_DEF_UNIT_MEMBER_CHIMERA',				0,       0,        null, 1.0,                1.0,				   null,			null,					null,					'ART_DEF_VEFFECT_FIGHTER_MACHINE_GUN_HIT_$(TERRAIN)',		0.25,			15,		   null,					   null,			1,				null,					 null,		   null,	  'BULLETHC',		'BULLETHC');
-- Chimera Dozer
INSERT INTO ArtDefine_UnitMemberCombatWeapons	(UnitMemberType,							"Index", SubIndex, ID,   VisKillStrengthMin, VisKillStrengthMax,   ProjectileSpeed, ProjectileTurnRateMin,	ProjectileTurnRateMax,	HitEffect,													HitEffectScale, HitRadius, ProjectileChildEffectScale, AreaDamageDelay, ContinuousFire, WaitForEffectCompletion, TargetGround, IsDropped, WeaponTypeTag,	WeaponTypeSoundOverrideTag)
VALUES											('ART_DEF_UNIT_MEMBER_CHIMERA_DOZER',		0,       0,        null, 1.0,                1.0,				   null,			null,					null,					'ART_DEF_VEFFECT_FIGHTER_MACHINE_GUN_HIT_$(TERRAIN)',		0.25,			15,		   null,					   null,			1,				null,					 null,		   null,	  'BULLETHC',		'BULLETHC');
-- Chimera Vetran  
INSERT INTO ArtDefine_UnitMemberCombatWeapons	(UnitMemberType,							"Index", SubIndex, ID,   VisKillStrengthMin, VisKillStrengthMax,   ProjectileSpeed, ProjectileTurnRateMin,	ProjectileTurnRateMax,	HitEffect,													HitEffectScale, HitRadius, ProjectileChildEffectScale, AreaDamageDelay, ContinuousFire, WaitForEffectCompletion, TargetGround, IsDropped, WeaponTypeTag,	WeaponTypeSoundOverrideTag)
VALUES											('ART_DEF_UNIT_MEMBER_CHIMERA_VET',			0,       0,        null, 1.0,                1.0,				   null,			null,					null,					'ART_DEF_VEFFECT_FIGHTER_MACHINE_GUN_HIT_$(TERRAIN)',		0.25,			15,		   null,					   null,			1,				null,					 null,		   null,	  'BULLETHC',		'BULLETHC');
-- Banewolf
INSERT INTO ArtDefine_UnitMemberCombatWeapons	(UnitMemberType,							"Index", SubIndex, ID,   VisKillStrengthMin, VisKillStrengthMax,   ProjectileSpeed, ProjectileTurnRateMin,	ProjectileTurnRateMax,	HitEffect,													HitEffectScale, HitRadius, ProjectileChildEffectScale, AreaDamageDelay, ContinuousFire, WaitForEffectCompletion, TargetGround, IsDropped, WeaponTypeTag,	WeaponTypeSoundOverrideTag)
VALUES											('ART_DEF_UNIT_MEMBER_BANEWOLF',			0,       0,        null, 25.0,               50.0,				   null,			null,					null,					'ART_DEF_VEFFECT_FLAMER_IMPACT',							null,			null, 	   null,					   null,			1,				null,					 null,		   null,	  'EXPLOSIVE',		'EXPLOSION20POUND');
-- Banewolf Sergeant
INSERT INTO ArtDefine_UnitMemberCombatWeapons	(UnitMemberType,							"Index", SubIndex, ID,   VisKillStrengthMin, VisKillStrengthMax,   ProjectileSpeed, ProjectileTurnRateMin,	ProjectileTurnRateMax,	HitEffect,													HitEffectScale, HitRadius, ProjectileChildEffectScale, AreaDamageDelay, ContinuousFire, WaitForEffectCompletion, TargetGround, IsDropped, WeaponTypeTag,	WeaponTypeSoundOverrideTag)
VALUES											('ART_DEF_UNIT_MEMBER_BANEWOLF_SGT',		0,       0,        null, 25.0,               50.0,				   null,			null,					null,					'ART_DEF_VEFFECT_FLAMER_IMPACT',							null,			null,	   null,					   null,			1,				null,					 null,		   null,	  'EXPLOSIVE',		'EXPLOSION20POUND');
-- Banewolf Vetran
INSERT INTO ArtDefine_UnitMemberCombatWeapons	(UnitMemberType,							"Index", SubIndex, ID,   VisKillStrengthMin, VisKillStrengthMax,   ProjectileSpeed, ProjectileTurnRateMin,	ProjectileTurnRateMax,	HitEffect,													HitEffectScale, HitRadius, ProjectileChildEffectScale, AreaDamageDelay, ContinuousFire, WaitForEffectCompletion, TargetGround, IsDropped, WeaponTypeTag,	WeaponTypeSoundOverrideTag)
VALUES											('ART_DEF_UNIT_MEMBER_BANEWOLF_VET',		0,       0,        null, 25.0,               50.0,				   null,			null,					null,					'ART_DEF_VEFFECT_FLAMER_IMPACT',							null,			null,	   null,					   null,			1,				null,					 null,		   null,	  'EXPLOSIVE',		'EXPLOSION20POUND');
-- Manitcore
INSERT INTO ArtDefine_UnitMemberCombatWeapons	(UnitMemberType,							"Index", SubIndex, ID,   VisKillStrengthMin, VisKillStrengthMax,   ProjectileSpeed, ProjectileTurnRateMin,	ProjectileTurnRateMax,	HitEffect,													HitEffectScale, HitRadius, ProjectileChildEffectScale, AreaDamageDelay, ContinuousFire, WaitForEffectCompletion, TargetGround, IsDropped, WeaponTypeTag,	WeaponTypeSoundOverrideTag)
VALUES											('ART_DEF_UNIT_MEMBER_MANTICORE',			0,       0,        null, 10.0,               15.0,				   2.0,			    null,					null,					null,														0.25,			null,	   null,					   null,			null,			null,					 null,		   null,	  'EXPLOSIVE',		'EXPLOSION20POUND');
-- Manitcore Dozer 
INSERT INTO ArtDefine_UnitMemberCombatWeapons	(UnitMemberType,							"Index", SubIndex, ID,   VisKillStrengthMin, VisKillStrengthMax,   ProjectileSpeed, ProjectileTurnRateMin,	ProjectileTurnRateMax,	HitEffect,													HitEffectScale, HitRadius, ProjectileChildEffectScale, AreaDamageDelay, ContinuousFire, WaitForEffectCompletion, TargetGround, IsDropped, WeaponTypeTag,	WeaponTypeSoundOverrideTag)
VALUES											('ART_DEF_UNIT_MEMBER_MANTICORE_DOZER',		0,       0,        null, 10.0,               15.0,				   2.0,			    null,					null,					null,														0.25,			null,	   null,					   null,			null,			null,					 null,		   null,	  'EXPLOSIVE',		'EXPLOSION20POUND');
-- Manitcore Vetran
INSERT INTO ArtDefine_UnitMemberCombatWeapons	(UnitMemberType,							"Index", SubIndex, ID,   VisKillStrengthMin, VisKillStrengthMax,   ProjectileSpeed, ProjectileTurnRateMin,	ProjectileTurnRateMax,	HitEffect,													HitEffectScale, HitRadius, ProjectileChildEffectScale, AreaDamageDelay, ContinuousFire, WaitForEffectCompletion, TargetGround, IsDropped, WeaponTypeTag,	WeaponTypeSoundOverrideTag)
VALUES											('ART_DEF_UNIT_MEMBER_MANTICORE_VET',		0,       0,        null, 10.0,               15.0,				   2.0,			    null,					null,					null,														0.25,			null,	   null,					   null,			null,			null,					 null,		   null,	  'EXPLOSIVE',		'EXPLOSION20POUND');
-- Baneblade
INSERT INTO ArtDefine_UnitMemberCombatWeapons	(UnitMemberType,							"Index", SubIndex, ID,   VisKillStrengthMin, VisKillStrengthMax,   ProjectileSpeed, ProjectileTurnRateMin,	ProjectileTurnRateMax,	HitEffect,													HitEffectScale, HitRadius, ProjectileChildEffectScale, AreaDamageDelay, ContinuousFire, WaitForEffectCompletion, TargetGround, IsDropped, WeaponTypeTag,	WeaponTypeSoundOverrideTag)
VALUES											('ART_DEF_UNIT_MEMBER_BANEBLADE',			0,       0,        null, 25.0,               50.0,				   null,			null,				    null,					'ART_DEF_VEFFECT_TANK_IMPACT_$(TERRAIN)',					0.25,			15,		   null,					   null,			1,				null,					 null,		   null,	  'EXPLOSIVE',		'EXPLOSION20POUND');
-- Leman Vanquisher
INSERT INTO ArtDefine_UnitMemberCombatWeapons	(UnitMemberType,							"Index", SubIndex, ID,   VisKillStrengthMin, VisKillStrengthMax,   ProjectileSpeed, ProjectileTurnRateMin,	ProjectileTurnRateMax,	HitEffect,													HitEffectScale, HitRadius, ProjectileChildEffectScale, AreaDamageDelay, ContinuousFire, WaitForEffectCompletion, TargetGround, IsDropped, WeaponTypeTag,	WeaponTypeSoundOverrideTag)
VALUES											('ART_DEF_UNIT_MEMBER_LEMAN_VANQ',			0,       0,        null, 25.0,               50.0,				   null,			null,					null,					'ART_DEF_VEFFECT_TANK_IMPACT_$(TERRAIN)',					0.25,			null,	   null,					   null,			null,			null,					 null,		   null,	  'EXPLOSIVE',		'EXPLOSION20POUND');
-- Leman Vanquisher Dozer
INSERT INTO ArtDefine_UnitMemberCombatWeapons	(UnitMemberType,							"Index", SubIndex, ID,   VisKillStrengthMin, VisKillStrengthMax,   ProjectileSpeed, ProjectileTurnRateMin,	ProjectileTurnRateMax,	HitEffect,													HitEffectScale, HitRadius, ProjectileChildEffectScale, AreaDamageDelay, ContinuousFire, WaitForEffectCompletion, TargetGround, IsDropped, WeaponTypeTag,	WeaponTypeSoundOverrideTag)
VALUES											('ART_DEF_UNIT_MEMBER_LEMAN_VANQ_DOZER',	0,       0,        null, 25.0,               50.0,				   null,			null,					null,					'ART_DEF_VEFFECT_TANK_IMPACT_$(TERRAIN)',					0.25,			null,	   null,					   null,			null,			null,					 null,		   null,	  'EXPLOSIVE',		'EXPLOSION20POUND');
-- Leman Exec
INSERT INTO ArtDefine_UnitMemberCombatWeapons	(UnitMemberType,							"Index", SubIndex, ID,   VisKillStrengthMin, VisKillStrengthMax,   ProjectileSpeed, ProjectileTurnRateMin,	ProjectileTurnRateMax,	HitEffect,													HitEffectScale, HitRadius, ProjectileChildEffectScale, AreaDamageDelay, ContinuousFire, WaitForEffectCompletion, TargetGround, IsDropped, WeaponTypeTag,	WeaponTypeSoundOverrideTag)
VALUES											('ART_DEF_UNIT_MEMBER_LEMAN_EXEC',			0,       0,        null, null,               null,				   2.5,			    null,					null,					null,														null,			null,	   null,					   null,			1,				null,					 null,		   null,	  'EXPLOSIVE',		'RAILGUN');
-- Leman Exec Dozer
INSERT INTO ArtDefine_UnitMemberCombatWeapons	(UnitMemberType,							"Index", SubIndex, ID,   VisKillStrengthMin, VisKillStrengthMax,   ProjectileSpeed, ProjectileTurnRateMin,	ProjectileTurnRateMax,	HitEffect,													HitEffectScale, HitRadius, ProjectileChildEffectScale, AreaDamageDelay, ContinuousFire, WaitForEffectCompletion, TargetGround, IsDropped, WeaponTypeTag,	WeaponTypeSoundOverrideTag)
VALUES											('ART_DEF_UNIT_MEMBER_LEMAN_EXEC_DOZER',	0,       0,        null, null,               null,				   2.5,			    null,					null,					null,														null,			null,	   null,					   null,			1,				null,					 null,		   null,	  'EXPLOSIVE',		'RAILGUN');
-- Leman 
INSERT INTO ArtDefine_UnitMemberCombatWeapons	(UnitMemberType,							"Index", SubIndex, ID,   VisKillStrengthMin, VisKillStrengthMax,   ProjectileSpeed, ProjectileTurnRateMin,	ProjectileTurnRateMax,	HitEffect,													HitEffectScale, HitRadius, ProjectileChildEffectScale, AreaDamageDelay, ContinuousFire, WaitForEffectCompletion, TargetGround, IsDropped, WeaponTypeTag,	WeaponTypeSoundOverrideTag)
VALUES											('ART_DEF_UNIT_MEMBER_LEMAN',				0,       0,        null, 25.0,               50.0,				   null,			null,					null,					'ART_DEF_VEFFECT_TANK_IMPACT_$(TERRAIN)',					0.25,			null,	   null,					   null,			1,				null,					 null,		   null,	  'EXPLOSIVE',		'EXPLOSION20POUND');
-- Leman Dozer
INSERT INTO ArtDefine_UnitMemberCombatWeapons	(UnitMemberType,							"Index", SubIndex, ID,   VisKillStrengthMin, VisKillStrengthMax,   ProjectileSpeed, ProjectileTurnRateMin,	ProjectileTurnRateMax,	HitEffect,													HitEffectScale, HitRadius, ProjectileChildEffectScale, AreaDamageDelay, ContinuousFire, WaitForEffectCompletion, TargetGround, IsDropped, WeaponTypeTag,	WeaponTypeSoundOverrideTag)
VALUES											('ART_DEF_UNIT_MEMBER_LEMAN_DOZER',			0,       0,        null, 25.0,               50.0,				   null,		    null,					null,					'ART_DEF_VEFFECT_TANK_IMPACT_$(TERRAIN)',					0.25,			null,	   null,					   null,			1,				null,					 null,		   null,	  'EXPLOSIVE',		'EXPLOSION20POUND');
-- Dread
INSERT INTO ArtDefine_UnitMemberCombatWeapons	(UnitMemberType,							"Index", SubIndex, ID,   VisKillStrengthMin, VisKillStrengthMax,   ProjectileSpeed, ProjectileTurnRateMin,	ProjectileTurnRateMax,	HitEffect,													HitEffectScale, HitRadius, ProjectileChildEffectScale, AreaDamageDelay, ContinuousFire, WaitForEffectCompletion, TargetGround, IsDropped, WeaponTypeTag,	WeaponTypeSoundOverrideTag)
VALUES											('ART_DEF_UNIT_MEMBER_DREAD',				0,       0,        null, 1.0,                1.0,				   null,			null,					null,					'ART_DEF_VEFFECT_GUNSHIP_MACHINE_GUN_HIT_$(TERRAIN)',		0.2,			15.0,	   null,					   null,			1,				null,					 null,		   null,	  'BULLETHC',		'BULLETHC');
-- Hellfire Dread
INSERT INTO ArtDefine_UnitMemberCombatWeapons	(UnitMemberType,							"Index", SubIndex, ID,   VisKillStrengthMin, VisKillStrengthMax,   ProjectileSpeed, ProjectileTurnRateMin,	ProjectileTurnRateMax,	HitEffect,													HitEffectScale, HitRadius, ProjectileChildEffectScale, AreaDamageDelay, ContinuousFire, WaitForEffectCompletion, TargetGround, IsDropped, WeaponTypeTag,	WeaponTypeSoundOverrideTag)
VALUES											('ART_DEF_UNIT_MEMBER_HELLFIRE_DREAD',		0,       0,        null, 1.0,                1.0,				   null,			null,					null,					'ART_DEF_VEFFECT_GUNSHIP_MACHINE_GUN_HIT_$(TERRAIN)',		0.2,			15.0,	   null,					   null,			1,				null,					 null,		   null,	  'BULLETHC',		'BULLETHC');
-- Ven Dread
INSERT INTO ArtDefine_UnitMemberCombatWeapons	(UnitMemberType,							"Index", SubIndex, ID,   VisKillStrengthMin, VisKillStrengthMax,   ProjectileSpeed, ProjectileTurnRateMin,	ProjectileTurnRateMax,	HitEffect,													HitEffectScale, HitRadius, ProjectileChildEffectScale, AreaDamageDelay, ContinuousFire, WaitForEffectCompletion, TargetGround, IsDropped, WeaponTypeTag,	WeaponTypeSoundOverrideTag)
VALUES											('ART_DEF_UNIT_MEMBER_VEN_DREAD',			0,       0,        null, 1.0,                1.0,				   null,			null,					null,					'ART_DEF_VEFFECT_GUNSHIP_MACHINE_GUN_HIT_$(TERRAIN)',		0.2,			15.0,	   null,					   null,			1,				null,					 null,		   null,	  'BULLETHC',		'BULLETHC');
-- Lictor
INSERT INTO ArtDefine_UnitMemberCombatWeapons	(UnitMemberType,							"Index", SubIndex, ID,   VisKillStrengthMin, VisKillStrengthMax,   ProjectileSpeed, ProjectileTurnRateMin,	ProjectileTurnRateMax,	HitEffect,													HitEffectScale, HitRadius, ProjectileChildEffectScale, AreaDamageDelay, ContinuousFire, WaitForEffectCompletion, TargetGround, IsDropped, WeaponTypeTag,	WeaponTypeSoundOverrideTag)
VALUES											('ART_DEF_UNIT_MEMBER_LICTOR',				0,	     0,        null, null,               null,				   null,			null,					null,					null,														null,			null,	   null,					   null,			null,			null,					 null,		   null,	  'BLUNT',			'BLUNT');

