-- Heavy
INSERT INTO ArtDefine_UnitMemberCombats	(UnitMemberType,							EnableActions,																									DisableActions, MoveRadius, ShortMoveRadius, ChargeRadius, AttackRadius, RangedAttackRadius, MoveRate, ShortMoveRate, TurnRateMin, TurnRateMax, TurnFacingRateMin, TurnFacingRateMax, RollRateMin, RollRateMax, PitchRateMin, PitchRateMax, LOSRadiusScale, TargetRadius, TargetHeight, HasShortRangedAttack, HasLongRangedAttack, HasLeftRightAttack, HasStationaryMelee, HasStationaryRangedAttack, HasRefaceAfterCombat, ReformBeforeCombat, HasIndependentWeaponFacing, HasOpponentTracking, HasCollisionAttack, AttackAltitude, AltitudeDecelerationDistance, OnlyTurnInMovementActions, RushAttackFormation) 
VALUES									('ART_DEF_UNIT_MEMBER_IG_HEAVY',			'Idle Attack RunCharge AttackCity Bombard Death BombardDefend Run Fortify CombatReady Walk AttackCharge',		null,			null,		null,			 null,		   null,		 null,				 null,	   null,		  null,		   null,		null,			   null,			  null,		   null,		null,		  null,			null,			null,		  null,			'1',				  null,				   null,			   null,			   null,					  null,				    '1',				null,						null,			     null,				 null,			 null,						   null,					  null);
-- Sergeant
INSERT INTO ArtDefine_UnitMemberCombats	(UnitMemberType,							EnableActions,																									DisableActions, MoveRadius, ShortMoveRadius, ChargeRadius, AttackRadius, RangedAttackRadius, MoveRate, ShortMoveRate, TurnRateMin, TurnRateMax, TurnFacingRateMin, TurnFacingRateMax, RollRateMin, RollRateMax, PitchRateMin, PitchRateMax, LOSRadiusScale, TargetRadius, TargetHeight, HasShortRangedAttack, HasLongRangedAttack, HasLeftRightAttack, HasStationaryMelee, HasStationaryRangedAttack, HasRefaceAfterCombat, ReformBeforeCombat, HasIndependentWeaponFacing, HasOpponentTracking, HasCollisionAttack, AttackAltitude, AltitudeDecelerationDistance, OnlyTurnInMovementActions, RushAttackFormation) 
VALUES									('ART_DEF_UNIT_MEMBER_IG_SGT',				'Idle Attack RunCharge AttackCity Bombard Death BombardDefend Run Fortify CombatReady Walk AttackCharge',		null,			null,		null,			 null,		   null,		 null,				 null,	   null,		  null,		   null,		null,			   null,			  null,		   null,		null,		  null,			null,			null,		  null,			null,				  null,				   null,			   null,			   null,					  null,				    '1',				null,						null,			     null,				 null,			 null,						   null,					  null);
-- Soldier
INSERT INTO ArtDefine_UnitMemberCombats	(UnitMemberType,							EnableActions,																									DisableActions, MoveRadius, ShortMoveRadius, ChargeRadius, AttackRadius, RangedAttackRadius, MoveRate, ShortMoveRate, TurnRateMin, TurnRateMax, TurnFacingRateMin, TurnFacingRateMax, RollRateMin, RollRateMax, PitchRateMin, PitchRateMax, LOSRadiusScale, TargetRadius, TargetHeight, HasShortRangedAttack, HasLongRangedAttack, HasLeftRightAttack, HasStationaryMelee, HasStationaryRangedAttack, HasRefaceAfterCombat, ReformBeforeCombat, HasIndependentWeaponFacing, HasOpponentTracking, HasCollisionAttack, AttackAltitude, AltitudeDecelerationDistance, OnlyTurnInMovementActions, RushAttackFormation) 
VALUES									('ART_DEF_UNIT_MEMBER_IG_SOLDIER',			'Idle Attack RunCharge AttackCity Bombard Death BombardDefend Run Fortify CombatReady Walk AttackCharge',		null,			null,		null,			 null,		   null,		 null,				 null,	   null,		  null,		   null,		null,			   null,			  null,		   null,		null,		  null,			null,			null,		  null,			'1',				  null,				   null,			   null,			   null,					  null,				    '1',				null,						null,			     null,				 null,			 null,						   null,					  null);
-- Trooper
INSERT INTO ArtDefine_UnitMemberCombats	(UnitMemberType,							EnableActions,																									DisableActions, MoveRadius, ShortMoveRadius, ChargeRadius, AttackRadius, RangedAttackRadius, MoveRate, ShortMoveRate, TurnRateMin, TurnRateMax, TurnFacingRateMin, TurnFacingRateMax, RollRateMin, RollRateMax, PitchRateMin, PitchRateMax, LOSRadiusScale, TargetRadius, TargetHeight, HasShortRangedAttack, HasLongRangedAttack, HasLeftRightAttack, HasStationaryMelee, HasStationaryRangedAttack, HasRefaceAfterCombat, ReformBeforeCombat, HasIndependentWeaponFacing, HasOpponentTracking, HasCollisionAttack, AttackAltitude, AltitudeDecelerationDistance, OnlyTurnInMovementActions, RushAttackFormation) 
VALUES									('ART_DEF_UNIT_MEMBER_IG_TROOPER',			'Idle Attack RunCharge AttackCity Bombard Death BombardDefend Run Fortify CombatReady Walk AttackCharge',		null,			null,		null,			 null,		   null,		 null,				 null,	   null,		  null,		   null,		null,			   null,			  null,		   null,		null,		  null,			null,			null,		  null,			null,				  null,				   null,			   null,			   null,					  null,				    '1',				null,						null,			     null,				 null,			 null,						   null,					  null);
-- Vetran
INSERT INTO ArtDefine_UnitMemberCombats	(UnitMemberType,							EnableActions,																									DisableActions, MoveRadius, ShortMoveRadius, ChargeRadius, AttackRadius, RangedAttackRadius, MoveRate, ShortMoveRate, TurnRateMin, TurnRateMax, TurnFacingRateMin, TurnFacingRateMax, RollRateMin, RollRateMax, PitchRateMin, PitchRateMax, LOSRadiusScale, TargetRadius, TargetHeight, HasShortRangedAttack, HasLongRangedAttack, HasLeftRightAttack, HasStationaryMelee, HasStationaryRangedAttack, HasRefaceAfterCombat, ReformBeforeCombat, HasIndependentWeaponFacing, HasOpponentTracking, HasCollisionAttack, AttackAltitude, AltitudeDecelerationDistance, OnlyTurnInMovementActions, RushAttackFormation) 
VALUES									('ART_DEF_UNIT_MEMBER_IG_VET',				'Idle Attack RunCharge AttackCity Bombard Death BombardDefend Run Fortify CombatReady Walk AttackCharge',		null,			null,		null,			 null,		   null,		 null,				 null,	   null,		  null,		   null,		null,			   null,			  null,		   null,		null,		  null,			null,			null,		  null,			null,				  null,				   null,			   null,			   null,					  null,				    '1',				null,						null,			     null,				 null,			 null,						   null,					  null);
-- Chimera
INSERT INTO ArtDefine_UnitMemberCombats	(UnitMemberType,							EnableActions,																									DisableActions, MoveRadius, ShortMoveRadius, ChargeRadius, AttackRadius, RangedAttackRadius, MoveRate, ShortMoveRate, TurnRateMin, TurnRateMax, TurnFacingRateMin, TurnFacingRateMax, RollRateMin, RollRateMax, PitchRateMin, PitchRateMax, LOSRadiusScale, TargetRadius, TargetHeight, HasShortRangedAttack, HasLongRangedAttack, HasLeftRightAttack, HasStationaryMelee, HasStationaryRangedAttack, HasRefaceAfterCombat, ReformBeforeCombat, HasIndependentWeaponFacing, HasOpponentTracking, HasCollisionAttack, AttackAltitude, AltitudeDecelerationDistance, OnlyTurnInMovementActions, RushAttackFormation) 
VALUES									('ART_DEF_UNIT_MEMBER_CHIMERA',				'Idle Attack RunCharge AttackCity Bombard Death BombardDefend Run Fortify CombatReady Walk AttackCharge',		null,			null,		null,			 null,		   null,		 null,				 null,	   null,		  null,		   null,		null,			   null,			  null,		   null,		null,		  null,			null,			null,		  null,			'1',				  null,				   null,			   '1',				   null,					  null,				    '1',				'1',						null,			     null,				 null,			 null,						   null,					  null);
-- Chimera Dozer
INSERT INTO ArtDefine_UnitMemberCombats	(UnitMemberType,							EnableActions,																									DisableActions, MoveRadius, ShortMoveRadius, ChargeRadius, AttackRadius, RangedAttackRadius, MoveRate, ShortMoveRate, TurnRateMin, TurnRateMax, TurnFacingRateMin, TurnFacingRateMax, RollRateMin, RollRateMax, PitchRateMin, PitchRateMax, LOSRadiusScale, TargetRadius, TargetHeight, HasShortRangedAttack, HasLongRangedAttack, HasLeftRightAttack, HasStationaryMelee, HasStationaryRangedAttack, HasRefaceAfterCombat, ReformBeforeCombat, HasIndependentWeaponFacing, HasOpponentTracking, HasCollisionAttack, AttackAltitude, AltitudeDecelerationDistance, OnlyTurnInMovementActions, RushAttackFormation) 
VALUES									('ART_DEF_UNIT_MEMBER_CHIMERA_DOZER',		'Idle Attack RunCharge AttackCity Bombard Death BombardDefend Run Fortify CombatReady Walk AttackCharge',		null,			null,		null,			 null,		   null,		 null,				 null,	   null,		  null,		   null,		null,			   null,			  null,		   null,		null,		  null,			null,			null,		  null,			'1',				  null,				   null,			   '1',				   null,					  null,				    '1',				'1',						null,			     null,				 null,			 null,						   null,					  null);
-- Chimera Vetran
INSERT INTO ArtDefine_UnitMemberCombats	(UnitMemberType,							EnableActions,																									DisableActions, MoveRadius, ShortMoveRadius, ChargeRadius, AttackRadius, RangedAttackRadius, MoveRate, ShortMoveRate, TurnRateMin, TurnRateMax, TurnFacingRateMin, TurnFacingRateMax, RollRateMin, RollRateMax, PitchRateMin, PitchRateMax, LOSRadiusScale, TargetRadius, TargetHeight, HasShortRangedAttack, HasLongRangedAttack, HasLeftRightAttack, HasStationaryMelee, HasStationaryRangedAttack, HasRefaceAfterCombat, ReformBeforeCombat, HasIndependentWeaponFacing, HasOpponentTracking, HasCollisionAttack, AttackAltitude, AltitudeDecelerationDistance, OnlyTurnInMovementActions, RushAttackFormation) 
VALUES									('ART_DEF_UNIT_MEMBER_CHIMERA_VET',			'Idle Attack RunCharge AttackCity Bombard Death BombardDefend Run Fortify CombatReady Walk AttackCharge',		null,			null,		null,			 null,		   null,		 null,				 null,	   null,		  null,		   null,		null,			   null,			  null,		   null,		null,		  null,			null,			null,		  null,			'1',				  null,				   null,			   '1',				   null,					  null,				    '1',				'1',						null,			     null,				 null,			 null,						   null,					  null);
-- Banewolf
INSERT INTO ArtDefine_UnitMemberCombats	(UnitMemberType,							EnableActions,																									DisableActions, MoveRadius, ShortMoveRadius, ChargeRadius, AttackRadius, RangedAttackRadius, MoveRate, ShortMoveRate, TurnRateMin, TurnRateMax, TurnFacingRateMin, TurnFacingRateMax, RollRateMin, RollRateMax, PitchRateMin, PitchRateMax, LOSRadiusScale, TargetRadius, TargetHeight, HasShortRangedAttack, HasLongRangedAttack, HasLeftRightAttack, HasStationaryMelee, HasStationaryRangedAttack, HasRefaceAfterCombat, ReformBeforeCombat, HasIndependentWeaponFacing, HasOpponentTracking, HasCollisionAttack, AttackAltitude, AltitudeDecelerationDistance, OnlyTurnInMovementActions, RushAttackFormation) 
VALUES									('ART_DEF_UNIT_MEMBER_BANEWOLF',			'Idle Attack RunCharge AttackCity Bombard Death BombardDefend Run Fortify CombatReady Walk AttackCharge',		null,			null,		null,			 null,		   null,		 null,				 null,	   null,		  null,		   null,		null,			   null,			  null,		   null,		null,		  null,			null,			null,		  null,			'1',				  null,				   null,			   '1',				   null,					  null,				    '1',				null,						null,			     null,				 null,			 null,						   null,					  null);
-- Banewolf SGT
INSERT INTO ArtDefine_UnitMemberCombats	(UnitMemberType,							EnableActions,																									DisableActions, MoveRadius, ShortMoveRadius, ChargeRadius, AttackRadius, RangedAttackRadius, MoveRate, ShortMoveRate, TurnRateMin, TurnRateMax, TurnFacingRateMin, TurnFacingRateMax, RollRateMin, RollRateMax, PitchRateMin, PitchRateMax, LOSRadiusScale, TargetRadius, TargetHeight, HasShortRangedAttack, HasLongRangedAttack, HasLeftRightAttack, HasStationaryMelee, HasStationaryRangedAttack, HasRefaceAfterCombat, ReformBeforeCombat, HasIndependentWeaponFacing, HasOpponentTracking, HasCollisionAttack, AttackAltitude, AltitudeDecelerationDistance, OnlyTurnInMovementActions, RushAttackFormation) 
VALUES									('ART_DEF_UNIT_MEMBER_BANEWOLF_SGT',		'Idle Attack RunCharge AttackCity Bombard Death BombardDefend Run Fortify CombatReady Walk AttackCharge',		null,			null,		null,			 null,		   null,		 null,				 null,	   null,		  null,		   null,		null,			   null,			  null,		   null,		null,		  null,			null,			null,		  null,			'1',				  null,				   null,			   '1',				   null,					  null,				    '1',				null,						null,			     null,				 null,			 null,						   null,					  null);
-- Banewolf Vetran
INSERT INTO ArtDefine_UnitMemberCombats	(UnitMemberType,							EnableActions,																									DisableActions, MoveRadius, ShortMoveRadius, ChargeRadius, AttackRadius, RangedAttackRadius, MoveRate, ShortMoveRate, TurnRateMin, TurnRateMax, TurnFacingRateMin, TurnFacingRateMax, RollRateMin, RollRateMax, PitchRateMin, PitchRateMax, LOSRadiusScale, TargetRadius, TargetHeight, HasShortRangedAttack, HasLongRangedAttack, HasLeftRightAttack, HasStationaryMelee, HasStationaryRangedAttack, HasRefaceAfterCombat, ReformBeforeCombat, HasIndependentWeaponFacing, HasOpponentTracking, HasCollisionAttack, AttackAltitude, AltitudeDecelerationDistance, OnlyTurnInMovementActions, RushAttackFormation) 
VALUES									('ART_DEF_UNIT_MEMBER_BANEWOLF_VET',		'Idle Attack RunCharge AttackCity Bombard Death BombardDefend Run Fortify CombatReady Walk AttackCharge',		null,			null,		null,			 null,		   null,		 null,				 null,	   null,		  null,		   null,		null,			   null,			  null,		   null,		null,		  null,			null,			null,		  null,			'1',				  null,				   null,			   '1',				   null,					  null,				    '1',				null,						null,			     null,				 null,			 null,						   null,					  null);
-- Manticore
INSERT INTO ArtDefine_UnitMemberCombats	(UnitMemberType,							EnableActions,																									DisableActions, MoveRadius, ShortMoveRadius, ChargeRadius, AttackRadius, RangedAttackRadius, MoveRate, ShortMoveRate, TurnRateMin, TurnRateMax, TurnFacingRateMin, TurnFacingRateMax, RollRateMin, RollRateMax, PitchRateMin, PitchRateMax, LOSRadiusScale, TargetRadius, TargetHeight, HasShortRangedAttack, HasLongRangedAttack, HasLeftRightAttack, HasStationaryMelee, HasStationaryRangedAttack, HasRefaceAfterCombat, ReformBeforeCombat, HasIndependentWeaponFacing, HasOpponentTracking, HasCollisionAttack, AttackAltitude, AltitudeDecelerationDistance, OnlyTurnInMovementActions, RushAttackFormation) 
VALUES									('ART_DEF_UNIT_MEMBER_MANTICORE',			'Idle Attack RunCharge AttackCity Bombard Death BombardDefend Run Fortify CombatReady Walk AttackCharge',		null,			null,		null,			 null,		   null,		 null,				 null,	   null,		  null,		   null,		null,			   null,			  null,		   null,		null,		  null,			null,			null,		  null,			'1',				  null,				   null,			   '1',				   null,					  null,				    '1',				null,						null,			     null,				 null,			 null,						   null,					  null);
-- Manticore Dozer
INSERT INTO ArtDefine_UnitMemberCombats	(UnitMemberType,							EnableActions,																									DisableActions, MoveRadius, ShortMoveRadius, ChargeRadius, AttackRadius, RangedAttackRadius, MoveRate, ShortMoveRate, TurnRateMin, TurnRateMax, TurnFacingRateMin, TurnFacingRateMax, RollRateMin, RollRateMax, PitchRateMin, PitchRateMax, LOSRadiusScale, TargetRadius, TargetHeight, HasShortRangedAttack, HasLongRangedAttack, HasLeftRightAttack, HasStationaryMelee, HasStationaryRangedAttack, HasRefaceAfterCombat, ReformBeforeCombat, HasIndependentWeaponFacing, HasOpponentTracking, HasCollisionAttack, AttackAltitude, AltitudeDecelerationDistance, OnlyTurnInMovementActions, RushAttackFormation) 
VALUES									('ART_DEF_UNIT_MEMBER_MANTICORE_DOZER',		'Idle Attack RunCharge AttackCity Bombard Death BombardDefend Run Fortify CombatReady Walk AttackCharge',		null,			null,		null,			 null,		   null,		 null,				 null,	   null,		  null,		   null,		null,			   null,			  null,		   null,		null,		  null,			null,			null,		  null,			'1',				  null,				   null,			   '1',				   null,					  null,				    '1',				null,						null,			     null,				 null,			 null,						   null,					  null);
-- Manticore Vetran
INSERT INTO ArtDefine_UnitMemberCombats	(UnitMemberType,							EnableActions,																									DisableActions, MoveRadius, ShortMoveRadius, ChargeRadius, AttackRadius, RangedAttackRadius, MoveRate, ShortMoveRate, TurnRateMin, TurnRateMax, TurnFacingRateMin, TurnFacingRateMax, RollRateMin, RollRateMax, PitchRateMin, PitchRateMax, LOSRadiusScale, TargetRadius, TargetHeight, HasShortRangedAttack, HasLongRangedAttack, HasLeftRightAttack, HasStationaryMelee, HasStationaryRangedAttack, HasRefaceAfterCombat, ReformBeforeCombat, HasIndependentWeaponFacing, HasOpponentTracking, HasCollisionAttack, AttackAltitude, AltitudeDecelerationDistance, OnlyTurnInMovementActions, RushAttackFormation) 
VALUES									('ART_DEF_UNIT_MEMBER_MANTICORE_VET',		'Idle Attack RunCharge AttackCity Bombard Death BombardDefend Run Fortify CombatReady Walk AttackCharge',		null,			null,		null,			 null,		   null,		 null,				 null,	   null,		  null,		   null,		null,			   null,			  null,		   null,		null,		  null,			null,			null,		  null,			'1',				  null,				   null,			   '1',				   null,					  null,				    '1',				null,						null,			     null,				 null,			 null,						   null,					  null);
-- Baneblade
INSERT INTO ArtDefine_UnitMemberCombats	(UnitMemberType,							EnableActions,																									DisableActions, MoveRadius, ShortMoveRadius, ChargeRadius, AttackRadius, RangedAttackRadius, MoveRate, ShortMoveRate, TurnRateMin, TurnRateMax, TurnFacingRateMin, TurnFacingRateMax, RollRateMin, RollRateMax, PitchRateMin, PitchRateMax, LOSRadiusScale, TargetRadius, TargetHeight, HasShortRangedAttack, HasLongRangedAttack, HasLeftRightAttack, HasStationaryMelee, HasStationaryRangedAttack, HasRefaceAfterCombat, ReformBeforeCombat, HasIndependentWeaponFacing, HasOpponentTracking, HasCollisionAttack, AttackAltitude, AltitudeDecelerationDistance, OnlyTurnInMovementActions, RushAttackFormation) 
VALUES									('ART_DEF_UNIT_MEMBER_BANEBLADE',			'Idle Attack RunCharge AttackCity Bombard Death BombardDefend Run Fortify CombatReady Walk AttackCharge',		null,			null,		null,			 null,		   null,		 null,				 null,	   null,		  null,		   null,		null,			   null,			  null,		   null,		null,		  null,			null,			null,		  null,			'1',				  null,				   null,			   '1',				   null,					  null,				    '1',				null,						null,			     null,				 null,			 null,						   null,					  null);
-- Leman Vanquisher
INSERT INTO ArtDefine_UnitMemberCombats	(UnitMemberType,							EnableActions,																									DisableActions, MoveRadius, ShortMoveRadius, ChargeRadius, AttackRadius, RangedAttackRadius, MoveRate, ShortMoveRate, TurnRateMin, TurnRateMax, TurnFacingRateMin, TurnFacingRateMax, RollRateMin, RollRateMax, PitchRateMin, PitchRateMax, LOSRadiusScale, TargetRadius, TargetHeight, HasShortRangedAttack, HasLongRangedAttack, HasLeftRightAttack, HasStationaryMelee, HasStationaryRangedAttack, HasRefaceAfterCombat, ReformBeforeCombat, HasIndependentWeaponFacing, HasOpponentTracking, HasCollisionAttack, AttackAltitude, AltitudeDecelerationDistance, OnlyTurnInMovementActions, RushAttackFormation) 
VALUES									('ART_DEF_UNIT_MEMBER_LEMAN_VANQ',			'Idle Attack RunCharge AttackCity Bombard Death BombardDefend Run Fortify CombatReady Walk AttackCharge',		null,			null,		null,			 null,		   null,		 null,				 null,	   null,		  null,		   null,		null,			   null,			  null,		   null,		null,		  null,			null,			null,		  null,			'1',				  null,				   null,			   '1',				   null,					  null,				    '1',				'1',						null,			     null,				 null,			 null,						   null,					  null);
-- Leman Vanquisher Dozer
INSERT INTO ArtDefine_UnitMemberCombats	(UnitMemberType,							EnableActions,																									DisableActions, MoveRadius, ShortMoveRadius, ChargeRadius, AttackRadius, RangedAttackRadius, MoveRate, ShortMoveRate, TurnRateMin, TurnRateMax, TurnFacingRateMin, TurnFacingRateMax, RollRateMin, RollRateMax, PitchRateMin, PitchRateMax, LOSRadiusScale, TargetRadius, TargetHeight, HasShortRangedAttack, HasLongRangedAttack, HasLeftRightAttack, HasStationaryMelee, HasStationaryRangedAttack, HasRefaceAfterCombat, ReformBeforeCombat, HasIndependentWeaponFacing, HasOpponentTracking, HasCollisionAttack, AttackAltitude, AltitudeDecelerationDistance, OnlyTurnInMovementActions, RushAttackFormation) 
VALUES									('ART_DEF_UNIT_MEMBER_LEMAN_VANQ_DOZER',	'Idle Attack RunCharge AttackCity Bombard Death BombardDefend Run Fortify CombatReady Walk AttackCharge',		null,			null,		null,			 null,		   null,		 null,				 null,	   null,		  null,		   null,		null,			   null,			  null,		   null,		null,		  null,			null,			null,		  null,			'1',				  null,				   null,			   '1',				   null,					  null,				    '1',				'1',						null,			     null,				 null,			 null,						   null,					  null);
-- Leman Exec
INSERT INTO ArtDefine_UnitMemberCombats	(UnitMemberType,							EnableActions,																									DisableActions, MoveRadius, ShortMoveRadius, ChargeRadius, AttackRadius, RangedAttackRadius, MoveRate, ShortMoveRate, TurnRateMin, TurnRateMax, TurnFacingRateMin, TurnFacingRateMax, RollRateMin, RollRateMax, PitchRateMin, PitchRateMax, LOSRadiusScale, TargetRadius, TargetHeight, HasShortRangedAttack, HasLongRangedAttack, HasLeftRightAttack, HasStationaryMelee, HasStationaryRangedAttack, HasRefaceAfterCombat, ReformBeforeCombat, HasIndependentWeaponFacing, HasOpponentTracking, HasCollisionAttack, AttackAltitude, AltitudeDecelerationDistance, OnlyTurnInMovementActions, RushAttackFormation) 
VALUES									('ART_DEF_UNIT_MEMBER_LEMAN_EXEC',			'Idle Attack RunCharge AttackCity Bombard Death BombardDefend Run Fortify CombatReady Walk AttackCharge',		null,			null,		null,			 null,		   null,		 null,				 null,	   null,		  null,		   null,		null,			   null,			  null,		   null,		null,		  null,			null,			null,		  null,			'1',				  null,				   null,			   '1',				   null,					  null,				    '1',				'1',						null,			     null,				 null,			 null,						   null,					  null);
-- Leman Exec Dozer
INSERT INTO ArtDefine_UnitMemberCombats	(UnitMemberType,							EnableActions,																									DisableActions, MoveRadius, ShortMoveRadius, ChargeRadius, AttackRadius, RangedAttackRadius, MoveRate, ShortMoveRate, TurnRateMin, TurnRateMax, TurnFacingRateMin, TurnFacingRateMax, RollRateMin, RollRateMax, PitchRateMin, PitchRateMax, LOSRadiusScale, TargetRadius, TargetHeight, HasShortRangedAttack, HasLongRangedAttack, HasLeftRightAttack, HasStationaryMelee, HasStationaryRangedAttack, HasRefaceAfterCombat, ReformBeforeCombat, HasIndependentWeaponFacing, HasOpponentTracking, HasCollisionAttack, AttackAltitude, AltitudeDecelerationDistance, OnlyTurnInMovementActions, RushAttackFormation) 
VALUES									('ART_DEF_UNIT_MEMBER_LEMAN_EXEC_DOZER',	'Idle Attack RunCharge AttackCity Bombard Death BombardDefend Run Fortify CombatReady Walk AttackCharge',		null,			null,		null,			 null,		   null,		 null,				 null,	   null,		  null,		   null,		null,			   null,			  null,		   null,		null,		  null,			null,			null,		  null,			'1',				  null,				   null,			   '1',				   null,					  null,				    '1',				'1',						null,			     null,				 null,			 null,						   null,					  null);
-- Leman
INSERT INTO ArtDefine_UnitMemberCombats	(UnitMemberType,							EnableActions,																									DisableActions, MoveRadius, ShortMoveRadius, ChargeRadius, AttackRadius, RangedAttackRadius, MoveRate, ShortMoveRate, TurnRateMin, TurnRateMax, TurnFacingRateMin, TurnFacingRateMax, RollRateMin, RollRateMax, PitchRateMin, PitchRateMax, LOSRadiusScale, TargetRadius, TargetHeight, HasShortRangedAttack, HasLongRangedAttack, HasLeftRightAttack, HasStationaryMelee, HasStationaryRangedAttack, HasRefaceAfterCombat, ReformBeforeCombat, HasIndependentWeaponFacing, HasOpponentTracking, HasCollisionAttack, AttackAltitude, AltitudeDecelerationDistance, OnlyTurnInMovementActions, RushAttackFormation) 
VALUES									('ART_DEF_UNIT_MEMBER_LEMAN',				'Idle Attack RunCharge AttackCity Bombard Death BombardDefend Run Fortify CombatReady Walk AttackCharge',		null,			null,		null,			 null,		   null,		 null,				 null,	   null,		  null,		   null,		null,			   null,			  null,		   null,		null,		  null,			null,			null,		  null,			'1',				  null,				   null,			   '1',				   null,					  null,				    '1',				'1',						null,			     null,				 null,			 null,						   null,					  null);
-- Leman Dozer
INSERT INTO ArtDefine_UnitMemberCombats	(UnitMemberType,							EnableActions,																									DisableActions, MoveRadius, ShortMoveRadius, ChargeRadius, AttackRadius, RangedAttackRadius, MoveRate, ShortMoveRate, TurnRateMin, TurnRateMax, TurnFacingRateMin, TurnFacingRateMax, RollRateMin, RollRateMax, PitchRateMin, PitchRateMax, LOSRadiusScale, TargetRadius, TargetHeight, HasShortRangedAttack, HasLongRangedAttack, HasLeftRightAttack, HasStationaryMelee, HasStationaryRangedAttack, HasRefaceAfterCombat, ReformBeforeCombat, HasIndependentWeaponFacing, HasOpponentTracking, HasCollisionAttack, AttackAltitude, AltitudeDecelerationDistance, OnlyTurnInMovementActions, RushAttackFormation) 
VALUES									('ART_DEF_UNIT_MEMBER_LEMAN_DOZER',			'Idle Attack RunCharge AttackCity Bombard Death BombardDefend Run Fortify CombatReady Walk AttackCharge',		null,			null,		null,			 null,		   null,		 null,				 null,	   null,		  null,		   null,		null,			   null,			  null,		   null,		null,		  null,			null,			null,		  null,			'1',				  null,				   null,			   '1',				   null,					  null,				    '1',				'1',						null,			     null,				 null,			 null,						   null,					  null);
-- Dread
INSERT INTO ArtDefine_UnitMemberCombats	(UnitMemberType,							EnableActions,																									DisableActions, MoveRadius, ShortMoveRadius, ChargeRadius, AttackRadius, RangedAttackRadius, MoveRate, ShortMoveRate, TurnRateMin, TurnRateMax, TurnFacingRateMin, TurnFacingRateMax, RollRateMin, RollRateMax, PitchRateMin, PitchRateMax, LOSRadiusScale, TargetRadius, TargetHeight, HasShortRangedAttack, HasLongRangedAttack, HasLeftRightAttack, HasStationaryMelee, HasStationaryRangedAttack, HasRefaceAfterCombat, ReformBeforeCombat, HasIndependentWeaponFacing, HasOpponentTracking, HasCollisionAttack, AttackAltitude, AltitudeDecelerationDistance, OnlyTurnInMovementActions, RushAttackFormation) 
VALUES									('ART_DEF_UNIT_MEMBER_DREAD',				'Idle Attack RunCharge AttackCity Bombard Death BombardDefend Run Fortify CombatReady Walk AttackCharge',		null,			null,		null,			 null,		   null,		 null,				 null,	   null,		  null,		   null,		null,			   null,			  null,		   null,		null,		  null,			null,			null,		  null,			'1',				  '1',				   null,			   null,			   null,					  null,				    '1',				null,						null,			     null,				 null,			 null,						   null,					  null);
-- Hellfire Dread
INSERT INTO ArtDefine_UnitMemberCombats	(UnitMemberType,							EnableActions,																									DisableActions, MoveRadius, ShortMoveRadius, ChargeRadius, AttackRadius, RangedAttackRadius, MoveRate, ShortMoveRate, TurnRateMin, TurnRateMax, TurnFacingRateMin, TurnFacingRateMax, RollRateMin, RollRateMax, PitchRateMin, PitchRateMax, LOSRadiusScale, TargetRadius, TargetHeight, HasShortRangedAttack, HasLongRangedAttack, HasLeftRightAttack, HasStationaryMelee, HasStationaryRangedAttack, HasRefaceAfterCombat, ReformBeforeCombat, HasIndependentWeaponFacing, HasOpponentTracking, HasCollisionAttack, AttackAltitude, AltitudeDecelerationDistance, OnlyTurnInMovementActions, RushAttackFormation) 
VALUES									('ART_DEF_UNIT_MEMBER_HELLFIRE_DREAD',		'Idle Attack RunCharge AttackCity Bombard Death BombardDefend Run Fortify CombatReady Walk AttackCharge',		null,			null,		null,			 null,		   null,		 null,				 null,	   null,		  null,		   null,		null,			   null,			  null,		   null,		null,		  null,			null,			null,		  null,			'1',				  '1',				   null,			   null,			   null,					  null,				    '1',				null,						null,			     null,				 null,			 null,						   null,					  null);
-- Ven Dread
INSERT INTO ArtDefine_UnitMemberCombats	(UnitMemberType,							EnableActions,																									DisableActions, MoveRadius, ShortMoveRadius, ChargeRadius, AttackRadius, RangedAttackRadius, MoveRate, ShortMoveRate, TurnRateMin, TurnRateMax, TurnFacingRateMin, TurnFacingRateMax, RollRateMin, RollRateMax, PitchRateMin, PitchRateMax, LOSRadiusScale, TargetRadius, TargetHeight, HasShortRangedAttack, HasLongRangedAttack, HasLeftRightAttack, HasStationaryMelee, HasStationaryRangedAttack, HasRefaceAfterCombat, ReformBeforeCombat, HasIndependentWeaponFacing, HasOpponentTracking, HasCollisionAttack, AttackAltitude, AltitudeDecelerationDistance, OnlyTurnInMovementActions, RushAttackFormation) 
VALUES									('ART_DEF_UNIT_MEMBER_VEN_DREAD',			'Idle Attack RunCharge AttackCity Bombard Death BombardDefend Run Fortify CombatReady Walk AttackCharge',		null,			null,		null,			 null,		   null,		 null,				 null,	   null,		  null,		   null,		null,			   null,			  null,		   null,		null,		  null,			null,			null,		  null,			'1',				  '1',				   null,			   null,			   null,					  null,				    '1',				null,						null,			     null,				 null,			 null,						   null,					  null);
