-- Delete Existing Table
DROP TABLE IF EXISTS Technology_Flavors;
-- Create New Table
CREATE TABLE Technology_Flavors ('TechType' text , 
								 'FlavorType' text , 
								 'Flavor' integer , foreign key (TechType) references Technologies(Type), foreign key (FlavorType) references Flavors(Type));
-- Polulate Table
INSERT INTO Technology_Flavors (	TechType,									FlavorType,									Flavor)
SELECT								'TECH_AGRICULTURE',							'FLAVOR_GROWTH',							5							UNION ALL
SELECT								'TECH_POTTERY',								'FLAVOR_GROWTH',							12							UNION ALL
SELECT								'TECH_POTTERY',								'FLAVOR_RELIGION',							1							UNION ALL
SELECT								'TECH_ANIMAL_HUSBANDRY',					'FLAVOR_MOBILE',							7							UNION ALL
SELECT								'TECH_ANIMAL_HUSBANDRY',					'FLAVOR_TILE_IMPROVEMENT',					2							UNION ALL
SELECT								'TECH_ARCHERY',								'FLAVOR_RANGED',							4							UNION ALL
SELECT								'TECH_ARCHERY',								'FLAVOR_OFFENSE',							1							UNION ALL
SELECT								'TECH_MINING',								'FLAVOR_PRODUCTION',						8							UNION ALL
SELECT								'TECH_MINING',								'FLAVOR_TILE_IMPROVEMENT',					5							UNION ALL
SELECT								'TECH_SAILING',								'FLAVOR_NAVAL',								4							UNION ALL
SELECT								'TECH_SAILING',								'FLAVOR_NAVAL_TILE_IMPROVEMENT',			6							UNION ALL
SELECT								'TECH_SAILING',								'FLAVOR_WONDER',							3							UNION ALL
SELECT								'TECH_SAILING',								'FLAVOR_NAVAL_RECON',						6							UNION ALL
SELECT								'TECH_CALENDAR',							'FLAVOR_WONDER',							6							UNION ALL
SELECT								'TECH_CALENDAR',							'FLAVOR_RELIGION',							2							UNION ALL
SELECT								'TECH_CALENDAR',							'FLAVOR_GOLD',								6							UNION ALL
SELECT								'TECH_WRITING',								'FLAVOR_SCIENCE',							12							UNION ALL
SELECT								'TECH_WRITING',								'FLAVOR_WONDER',							6							UNION ALL
SELECT								'TECH_WRITING',								'FLAVOR_DIPLOMACY',							1							UNION ALL
SELECT								'TECH_TRAPPING',							'FLAVOR_GOLD',								8							UNION ALL
SELECT								'TECH_TRAPPING',							'FLAVOR_TILE_IMPROVEMENT',					2							UNION ALL
SELECT								'TECH_TRAPPING',							'FLAVOR_HAPPINESS',							3							UNION ALL
SELECT								'TECH_THE_WHEEL',							'FLAVOR_MOBILE',							3							UNION ALL
SELECT								'TECH_THE_WHEEL',							'FLAVOR_INFRASTRUCTURE',					6							UNION ALL
SELECT								'TECH_THE_WHEEL',							'FLAVOR_GOLD',								6							UNION ALL
SELECT								'TECH_MASONRY',								'FLAVOR_CITY_DEFENSE',						6							UNION ALL
SELECT								'TECH_MASONRY',								'FLAVOR_TILE_IMPROVEMENT',					6							UNION ALL
SELECT								'TECH_MASONRY',								'FLAVOR_WONDER',							5							UNION ALL
SELECT								'TECH_BRONZE_WORKING',						'FLAVOR_DEFENSE',							8							UNION ALL
SELECT								'TECH_OPTICS',								'FLAVOR_NAVAL',								3							UNION ALL
SELECT								'TECH_OPTICS',								'FLAVOR_SCIENCE',							4							UNION ALL
SELECT								'TECH_HORSEBACK_RIDING',					'FLAVOR_MOBILE',							10							UNION ALL
SELECT								'TECH_HORSEBACK_RIDING',					'FLAVOR_OFFENSE',							5							UNION ALL
SELECT								'TECH_HORSEBACK_RIDING',					'FLAVOR_PRODUCTION',						3							UNION ALL
SELECT								'TECH_MATHEMATICS',							'FLAVOR_WONDER',							6							UNION ALL
SELECT								'TECH_CONSTRUCTION',						'FLAVOR_HAPPINESS',							6							UNION ALL
SELECT								'TECH_CONSTRUCTION',						'FLAVOR_PRODUCTION',						5							UNION ALL
SELECT								'TECH_CONSTRUCTION',						'FLAVOR_WONDER',							5							UNION ALL
SELECT								'TECH_CONSTRUCTION',						'FLAVOR_TILE_IMPROVEMENT',					6							UNION ALL
SELECT								'TECH_PHILOSOPHY',							'FLAVOR_SCIENCE',							6							UNION ALL
SELECT								'TECH_PHILOSOPHY',							'FLAVOR_CULTURE',							6							UNION ALL
SELECT								'TECH_PHILOSOPHY',							'FLAVOR_RELIGION',							2							UNION ALL
SELECT								'TECH_PHILOSOPHY',							'FLAVOR_WONDER',							12							UNION ALL
SELECT								'TECH_DRAMA',								'FLAVOR_CULTURE',							6							UNION ALL
SELECT								'TECH_DRAMA',								'FLAVOR_GREAT_PEOPLE',						3							UNION ALL
SELECT								'TECH_CURRENCY',							'FLAVOR_GOLD',								20							UNION ALL
SELECT								'TECH_CURRENCY',							'FLAVOR_WONDER',							8							UNION ALL
SELECT								'TECH_IRON_WORKING',						'FLAVOR_OFFENSE',							12							UNION ALL
SELECT								'TECH_IRON_WORKING',						'FLAVOR_DEFENSE',							3							UNION ALL
SELECT								'TECH_IRON_WORKING',						'FLAVOR_MILITARY_TRAINING',					3							UNION ALL
SELECT								'TECH_THEOLOGY',							'FLAVOR_RELIGION',							6							UNION ALL
SELECT								'TECH_THEOLOGY',							'FLAVOR_GREAT_PEOPLE',						2							UNION ALL
SELECT								'TECH_THEOLOGY',							'FLAVOR_WONDER',							9							UNION ALL
SELECT								'TECH_CIVIL_SERVICE',						'FLAVOR_WONDER',							8							UNION ALL
SELECT								'TECH_GUILDS',								'FLAVOR_GOLD',								20							UNION ALL
SELECT								'TECH_GUILDS',								'FLAVOR_WONDER',							2							UNION ALL
SELECT								'TECH_ENGINEERING',							'FLAVOR_GROWTH',							7							UNION ALL
SELECT								'TECH_ENGINEERING',							'FLAVOR_INFRASTRUCTURE',					2							UNION ALL
SELECT								'TECH_METAL_CASTING',						'FLAVOR_PRODUCTION',6							UNION ALL
SELECT								'TECH_COMPASS',								'FLAVOR_GOLD',7							UNION ALL
SELECT								'TECH_COMPASS',								'FLAVOR_PRODUCTION',1							UNION ALL
SELECT								'TECH_COMPASS',								'FLAVOR_NAVAL',7							UNION ALL
SELECT								'TECH_COMPASS',								'FLAVOR_WATER_CONNECTION',8							UNION ALL
SELECT								'TECH_EDUCATION',							'FLAVOR_SCIENCE',15							UNION ALL
SELECT								'TECH_EDUCATION',							'FLAVOR_WONDER',6							UNION ALL
SELECT								'TECH_EDUCATION',							'FLAVOR_DIPLOMACY',4							UNION ALL
SELECT								'TECH_CHIVALRY',							'FLAVOR_OFFENSE',6							UNION ALL
SELECT								'TECH_CHIVALRY',							'FLAVOR_MOBILE',8							UNION ALL
SELECT								'TECH_CHIVALRY',							'FLAVOR_CITY_DEFENSE',4							UNION ALL
SELECT								'TECH_CHIVALRY',							'FLAVOR_WONDER',3							UNION ALL
SELECT								'TECH_CHIVALRY',							'FLAVOR_DIPLOMACY',2							UNION ALL
SELECT								'TECH_MACHINERY',							'FLAVOR_INFRASTRUCTURE',4							UNION ALL
SELECT								'TECH_MACHINERY',							'FLAVOR_PRODUCTION',2							UNION ALL
SELECT								'TECH_MACHINERY',							'FLAVOR_DEFENSE',3							UNION ALL
SELECT								'TECH_PHYSICS',								'FLAVOR_OFFENSE',5							UNION ALL
SELECT								'TECH_PHYSICS',								'FLAVOR_WONDER',2							UNION ALL
SELECT								'TECH_STEEL',								'FLAVOR_MILITARY_TRAINING',5							UNION ALL
SELECT								'TECH_ASTRONOMY',							'FLAVOR_NAVAL_RECON',16							UNION ALL
SELECT								'TECH_ASTRONOMY',							'FLAVOR_NAVAL',5							UNION ALL
SELECT								'TECH_ASTRONOMY',							'FLAVOR_SCIENCE',8							UNION ALL
SELECT								'TECH_ASTRONOMY',							'FLAVOR_EXPANSION',9							UNION ALL
SELECT								'TECH_ACOUSTICS',							'FLAVOR_CULTURE',7							UNION ALL
SELECT								'TECH_ACOUSTICS',							'FLAVOR_WONDER',7							UNION ALL
SELECT								'TECH_BANKING',								'FLAVOR_GOLD',25							UNION ALL
SELECT								'TECH_BANKING',								'FLAVOR_EXPANSION',3							UNION ALL
SELECT								'TECH_BANKING',								'FLAVOR_HAPPINESS',2							UNION ALL
SELECT								'TECH_BANKING',								'FLAVOR_WONDER',6							UNION ALL
SELECT								'TECH_PRINTING_PRESS',						'FLAVOR_WONDER',3							UNION ALL
SELECT								'TECH_PRINTING_PRESS',						'FLAVOR_GREAT_PEOPLE',2							UNION ALL
SELECT								'TECH_GUNPOWDER',							'FLAVOR_DEFENSE',12							UNION ALL
SELECT								'TECH_GUNPOWDER',							'FLAVOR_OFFENSE',6							UNION ALL
SELECT								'TECH_GUNPOWDER',							'FLAVOR_WONDER',2							UNION ALL
SELECT								'TECH_NAVIGATION',							'FLAVOR_NAVAL',20							UNION ALL
SELECT								'TECH_NAVIGATION',							'FLAVOR_PRODUCTION',4							UNION ALL
SELECT								'TECH_ARCHITECTURE',						'FLAVOR_WONDER',12							UNION ALL
SELECT								'TECH_ARCHITECTURE',						'FLAVOR_SCIENCE',12							UNION ALL
SELECT								'TECH_ECONOMICS',							'FLAVOR_GOLD',20							UNION ALL
SELECT								'TECH_CHEMISTRY',							'FLAVOR_RANGED',20							UNION ALL
SELECT								'TECH_CHEMISTRY',							'FLAVOR_OFFENSE',6							UNION ALL
SELECT								'TECH_CHEMISTRY',							'FLAVOR_DEFENSE',3							UNION ALL
SELECT								'TECH_METALLURGY',							'FLAVOR_OFFENSE',14							UNION ALL
SELECT								'TECH_METALLURGY',							'FLAVOR_MOBILE',3							UNION ALL
SELECT								'TECH_METALLURGY',							'FLAVOR_DEFENSE',4							UNION ALL
SELECT								'TECH_METALLURGY',							'FLAVOR_CITY_DEFENSE',3							UNION ALL
SELECT								'TECH_ARCHAEOLOGY',							'FLAVOR_CULTURE',12							UNION ALL
SELECT								'TECH_ARCHAEOLOGY',							'FLAVOR_WONDER',6							UNION ALL
SELECT								'TECH_ARCHAEOLOGY',							'FLAVOR_GREAT_PEOPLE',2							UNION ALL
SELECT								'TECH_SCIENTIFIC_THEORY',					'FLAVOR_SCIENCE',20							UNION ALL
SELECT								'TECH_INDUSTRIALIZATION',					'FLAVOR_PRODUCTION',20							UNION ALL
SELECT								'TECH_INDUSTRIALIZATION',					'FLAVOR_WONDER',2							UNION ALL
SELECT								'TECH_MILITARY_SCIENCE',					'FLAVOR_OFFENSE',12							UNION ALL
SELECT								'TECH_MILITARY_SCIENCE',					'FLAVOR_MILITARY_TRAINING',6							UNION ALL
SELECT								'TECH_MILITARY_SCIENCE',					'FLAVOR_WONDER',1							UNION ALL
SELECT								'TECH_FERTILIZER',							'FLAVOR_GOLD',4							UNION ALL
SELECT								'TECH_FERTILIZER',							'FLAVOR_GREAT_PEOPLE',5							UNION ALL
SELECT								'TECH_RIFLING',								'FLAVOR_DEFENSE',13							UNION ALL
SELECT								'TECH_RIFLING',								'FLAVOR_OFFENSE',13							UNION ALL
SELECT								'TECH_RIFLING',								'FLAVOR_CITY_DEFENSE',5							UNION ALL
SELECT								'TECH_BIOLOGY',								'FLAVOR_GROWTH',10							UNION ALL
SELECT								'TECH_BIOLOGY',								'FLAVOR_TILE_IMPROVEMENT',5							UNION ALL
SELECT								'TECH_BIOLOGY',								'FLAVOR_OFFENSE',3							UNION ALL
SELECT								'TECH_BIOLOGY',								'FLAVOR_DEFENSE',10							UNION ALL
SELECT								'TECH_BIOLOGY',								'FLAVOR_NAVAL',12							UNION ALL
SELECT								'TECH_BIOLOGY',								'FLAVOR_AIR',20							UNION ALL
SELECT								'TECH_STEAM_POWER',							'FLAVOR_NAVAL',2							UNION ALL
SELECT								'TECH_ELECTRICITY',							'FLAVOR_OFFENSE',5							UNION ALL
SELECT								'TECH_REPLACEABLE_PARTS',					'FLAVOR_WONDER',4							UNION ALL
SELECT								'TECH_RAILROAD',							'FLAVOR_INFRASTRUCTURE',10							UNION ALL
SELECT								'TECH_RAILROAD',							'FLAVOR_PRODUCTION',4							UNION ALL
SELECT								'TECH_RAILROAD',							'FLAVOR_WONDER',2							UNION ALL
SELECT								'TECH_REFRIGERATION','FLAVOR_NAVAL_TILE_IMPROVEMENT',5							UNION ALL
SELECT								'TECH_RADIO','FLAVOR_CULTURE',15							UNION ALL
SELECT								'TECH_RADIO','FLAVOR_WONDER',3							UNION ALL
SELECT								'TECH_FLIGHT','FLAVOR_AIR',15							UNION ALL
SELECT								'TECH_FLIGHT','FLAVOR_ANTIAIR',5							UNION ALL
SELECT								'TECH_BALLISTICS','FLAVOR_OFFENSE',10							UNION ALL
SELECT								'TECH_BALLISTICS','FLAVOR_ANTIAIR',5							UNION ALL
SELECT								'TECH_BALLISTICS','FLAVOR_DEFENSE',10							UNION ALL
SELECT								'TECH_COMBUSTION','FLAVOR_OFFENSE',5							UNION ALL
SELECT								'TECH_COMBUSTION','FLAVOR_MOBILE',2							UNION ALL
SELECT								'TECH_COMBUSTION','FLAVOR_NAVAL',5							UNION ALL
SELECT								'TECH_PLASTIC','FLAVOR_DEFENSE',10							UNION ALL
SELECT								'TECH_PLASTIC','FLAVOR_SCIENCE',5							UNION ALL
SELECT								'TECH_PLASTIC','FLAVOR_SPACESHIP',5							UNION ALL
SELECT								'TECH_ELECTRONICS','FLAVOR_NAVAL',10							UNION ALL
SELECT								'TECH_ELECTRONICS','FLAVOR_OFFENSE',5							UNION ALL
SELECT								'TECH_ELECTRONICS','FLAVOR_AIR_CARRIER',5							UNION ALL
SELECT								'TECH_RADAR','FLAVOR_AIR',15							UNION ALL
SELECT								'TECH_RADAR','FLAVOR_ANTIAIR',5							UNION ALL
SELECT								'TECH_COMBINED_ARMS','FLAVOR_OFFENSE',10							UNION ALL
SELECT								'TECH_COMBINED_ARMS','FLAVOR_MOBILE',10							UNION ALL
SELECT								'TECH_COMBINED_ARMS','FLAVOR_DEFENSE',5							UNION ALL
SELECT								'TECH_ATOMIC_THEORY','FLAVOR_NUKE',25							UNION ALL
SELECT								'TECH_ATOMIC_THEORY','FLAVOR_OFFENSE',10							UNION ALL
SELECT								'TECH_ECOLOGY','FLAVOR_PRODUCTION',8							UNION ALL
SELECT								'TECH_COMPUTERS','FLAVOR_AIR',5							UNION ALL
SELECT								'TECH_COMPUTERS','FLAVOR_NAVAL',5							UNION ALL
SELECT								'TECH_COMPUTERS','FLAVOR_NUKE',5							UNION ALL
SELECT								'TECH_TELECOM','FLAVOR_WONDER',5							UNION ALL
SELECT								'TECH_TELECOM','FLAVOR_DEFENSE',5							UNION ALL
SELECT								'TECH_ROCKETRY','FLAVOR_RANGED',10							UNION ALL
SELECT								'TECH_ROCKETRY','FLAVOR_AIR',5							UNION ALL
SELECT								'TECH_ROCKETRY','FLAVOR_MOBILE',5							UNION ALL
SELECT								'TECH_ROCKETRY','FLAVOR_SPACESHIP',30							UNION ALL
SELECT								'TECH_LASERS','FLAVOR_OFFENSE',5							UNION ALL
SELECT								'TECH_LASERS','FLAVOR_MOBILE',5							UNION ALL
SELECT								'TECH_LASERS','FLAVOR_AIR',5							UNION ALL
SELECT								'TECH_NUCLEAR_FISSION','FLAVOR_NUKE',30							UNION ALL
SELECT								'TECH_NUCLEAR_FISSION','FLAVOR_OFFENSE',5							UNION ALL
SELECT								'TECH_NUCLEAR_FISSION','FLAVOR_PRODUCTION',10							UNION ALL
SELECT								'TECH_GLOBALIZATION','FLAVOR_DIPLOMACY',50							UNION ALL
SELECT								'TECH_ROBOTICS','FLAVOR_NAVAL',4							UNION ALL
SELECT								'TECH_ROBOTICS','FLAVOR_SPACESHIP',25							UNION ALL
SELECT								'TECH_SATELLITES','FLAVOR_SCIENCE',6							UNION ALL
SELECT								'TECH_SATELLITES','FLAVOR_WONDER',2							UNION ALL
SELECT								'TECH_SATELLITES','FLAVOR_SPACESHIP',10							UNION ALL
SELECT								'TECH_STEALTH','FLAVOR_AIR',10							UNION ALL
SELECT								'TECH_MOBILE_TACTICS','FLAVOR_MOBILE',10							UNION ALL
SELECT								'TECH_MOBILE_TACTICS','FLAVOR_DEFENSE',10							UNION ALL
SELECT								'TECH_ADVANCED_BALLISTICS','FLAVOR_NUKE',10							UNION ALL
SELECT								'TECH_ADVANCED_BALLISTICS','FLAVOR_SPACESHIP',10							UNION ALL
SELECT								'TECH_PARTICLE_PHYSICS','FLAVOR_SPACESHIP',20							UNION ALL
SELECT								'TECH_NUCLEAR_FUSION','FLAVOR_OFFENSE',15							UNION ALL
SELECT								'TECH_NUCLEAR_FUSION','FLAVOR_NUKE',5							UNION ALL
SELECT								'TECH_NANOTECHNOLOGY','FLAVOR_SPACESHIP',20							UNION ALL
SELECT								'TECH_FUTURE_TECH','FLAVOR_SCIENCE',10							UNION ALL
SELECT								'TECH_ECONOMY_OF_SCALE','FLAVOR_GOLD',8							UNION ALL
SELECT								'TECH_ECONOMY_OF_SCALE','FLAVOR_TILE_IMPROVEMENT',10							UNION ALL
SELECT								'TECH_ECONOMY_OF_SCALE','FLAVOR_HAPPINESS',10							UNION ALL
SELECT								'TECH_FERMENTATION','FLAVOR_HAPPINESS',3							UNION ALL
SELECT								'TECH_FERMENTATION','FLAVOR_GOLD',2							UNION ALL
SELECT								'TECH_FERMENTATION','FLAVOR_TILE_IMPROVEMENT',2							UNION ALL
SELECT								'TECH_TRAPPING','FLAVOR_HAPPINESS',6							UNION ALL
SELECT								'TECH_TRADING','FLAVOR_TILE_IMPROVEMENT',4							UNION ALL
SELECT								'TECH_TRADING','FLAVOR_GOLD',15							UNION ALL
SELECT								'TECH_HERDING','FLAVOR_GROWTH',10							UNION ALL
SELECT								'TECH_APOTHECARY','FLAVOR_GROWTH',2							UNION ALL
SELECT								'TECH_APOTHECARY','FLAVOR_GOLD',4							UNION ALL
SELECT								'TECH_APOTHECARY','FLAVOR_SCIENCE',8							UNION ALL
SELECT								'TECH_DIVISION_OF_LABOR','FLAVOR_PRODUCTION',16							UNION ALL
SELECT								'TECH_DIVISION_OF_LABOR','FLAVOR_INFRASTRUCTURE',2							UNION ALL
SELECT								'TECH_ANIMAL_MARKETS','FLAVOR_GROWTH',8							UNION ALL
SELECT								'TECH_ANIMAL_MARKETS','FLAVOR_PRODUCTION',2							UNION ALL
SELECT								'TECH_ANIMAL_MARKETS','FLAVOR_GOLD',2							UNION ALL
SELECT								'TECH_FISH_MARKETS','FLAVOR_NAVAL_TILE_IMPROVEMENT',3							UNION ALL
SELECT								'TECH_FISH_MARKETS','FLAVOR_GROWTH',6							UNION ALL
SELECT								'TECH_FISH_MARKETS','FLAVOR_GOLD',6							UNION ALL
SELECT								'TECH_FARMERS_MARKETS','FLAVOR_GROWTH',8							UNION ALL
SELECT								'TECH_FARMERS_MARKETS','FLAVOR_GOLD',3							UNION ALL
SELECT								'TECH_TRADE_FAIRS','FLAVOR_GOLD',12							UNION ALL
SELECT								'TECH_TRADE_FAIRS','FLAVOR_WONDER',2							UNION ALL
SELECT								'TECH_COFFEE_TRADE','FLAVOR_GOLD',7							UNION ALL
SELECT								'TECH_COFFEE_TRADE','FLAVOR_TILE_IMPROVEMENT',NULL							UNION ALL
SELECT								'TECH_AGRICULTURAL_REVOLUTION','FLAVOR_GOLD',1							UNION ALL
SELECT								'TECH_AGRICULTURAL_REVOLUTION','FLAVOR_TILE_IMPROVEMENT',2							UNION ALL
SELECT								'TECH_AGRICULTURAL_REVOLUTION','FLAVOR_PRODUCTION',8							UNION ALL
SELECT								'TECH_AGRICULTURAL_REVOLUTION','FLAVOR_GROWTH',8							UNION ALL
SELECT								'TECH_LIVESTOCK_DISTRIBUTION','FLAVOR_GROWTH',10							UNION ALL
SELECT								'TECH_LIVESTOCK_DISTRIBUTION','FLAVOR_PRODUCTION',4							UNION ALL
SELECT								'TECH_LIVESTOCK_DISTRIBUTION','FLAVOR_GOLD',3							UNION ALL
SELECT								'TECH_BONDS','FLAVOR_WONDER',2							UNION ALL
SELECT								'TECH_BONDS','FLAVOR_GOLD',14							UNION ALL
SELECT								'TECH_OCEAN_PIONEERING','FLAVOR_GROWTH',8							UNION ALL
SELECT								'TECH_OCEAN_PIONEERING','FLAVOR_GOLD',6							UNION ALL
SELECT								'TECH_OCEAN_PIONEERING','FLAVOR_NAVAL',8							UNION ALL
SELECT								'TECH_STEEL','FLAVOR_TILE_IMPROVEMENT',2							UNION ALL
SELECT								'TECH_INTERNATIONAL_TRADE','FLAVOR_GROWTH',9							UNION ALL
SELECT								'TECH_INTERNATIONAL_TRADE','FLAVOR_PRODUCTION',5							UNION ALL
SELECT								'TECH_INTERNATIONAL_TRADE','FLAVOR_SCIENCE',5							UNION ALL
SELECT								'TECH_INTERNATIONAL_TRADE','FLAVOR_GOLD',5							UNION ALL
SELECT								'TECH_FERTILIZER','FLAVOR_TILE_IMPROVEMENT',2							UNION ALL
SELECT								'TECH_CORPORATIONS','FLAVOR_TILE_IMPROVEMENT',10							UNION ALL
SELECT								'TECH_CORPORATIONS','FLAVOR_GOLD',8							UNION ALL
SELECT								'TECH_REFRIGERATION','FLAVOR_TILE_IMPROVEMENT',3							UNION ALL
SELECT								'TECH_REFRIGERATION','FLAVOR_GROWTH',20							UNION ALL
SELECT								'TECH_INDUSTRIAL_PROCESSES','FLAVOR_TILE_IMPROVEMENT',1							UNION ALL
SELECT								'TECH_INDUSTRIAL_PROCESSES','FLAVOR_GOLD',10							UNION ALL
SELECT								'TECH_INDUSTRIAL_PROCESSES','FLAVOR_GROWTH',9							UNION ALL
SELECT								'TECH_INDUSTRIAL_PROCESSES','FLAVOR_PRODUCTION',3							UNION ALL
SELECT								'TECH_MINING','FLAVOR_WONDER',5							UNION ALL
SELECT								'TECH_MINING','FLAVOR_GREAT_PEOPLE',1							UNION ALL
SELECT								'TECH_MINING','FLAVOR_GOLD',1							UNION ALL
SELECT								'TECH_RAW_MATERIALS','FLAVOR_PRODUCTION',12							UNION ALL
SELECT								'TECH_GREAT_MONUMENTS','FLAVOR_WONDER',9							UNION ALL
SELECT								'TECH_STONE_MASONS','FLAVOR_PRODUCTION',9							UNION ALL
SELECT								'TECH_STONE_MASONS','FLAVOR_GOLD',3							UNION ALL
SELECT								'TECH_STONE_MASONS','FLAVOR_SCIENCE',2							UNION ALL
SELECT								'TECH_PUBLIC_WORKS','FLAVOR_HAPPINESS',20							UNION ALL
SELECT								'TECH_PUBLIC_WORKS','FLAVOR_GROWTH',5							UNION ALL
SELECT								'TECH_WOODWORKING','FLAVOR_PRODUCTION',10							UNION ALL
SELECT								'TECH_WOODWORKING','FLAVOR_RANGED',4							UNION ALL
SELECT								'TECH_WOODWORKING','FLAVOR_OFFENSE',6							UNION ALL
SELECT								'TECH_ENGINEERING','FLAVOR_TILE_IMPROVEMENT',6							UNION ALL
SELECT								'TECH_ENGINEERING','FLAVOR_MOBILE',2							UNION ALL
SELECT								'TECH_ENGINEERING','FLAVOR_EXPANSION',3							UNION ALL
SELECT								'TECH_ENGINEERING','FLAVOR_WONDER',2							UNION ALL
SELECT								'TECH_MACHINERY','FLAVOR_WONDER',4							UNION ALL
SELECT								'TECH_MACHINERY','FLAVOR_GOLD',8							UNION ALL
SELECT								'TECH_MACHINERY','FLAVOR_MOBILE',1							UNION ALL
SELECT								'TECH_BLAST_FURNACE','FLAVOR_PRODUCTION',14							UNION ALL
SELECT								'TECH_BLAST_FURNACE','FLAVOR_INFRASTRUCTURE',4							UNION ALL
SELECT								'TECH_DYNAMITE','FLAVOR_TILE_IMPROVEMENT',20							UNION ALL
SELECT								'TECH_STEAM_POWER','FLAVOR_TILE_IMPROVEMENT',1							UNION ALL
SELECT								'TECH_REPLACEABLE_PARTS','FLAVOR_PRODUCTION',6							UNION ALL
SELECT								'TECH_RAILROAD','FLAVOR_WONDER',4							UNION ALL
SELECT								'TECH_RAILROAD','FLAVOR_TILE_IMPROVEMENT',1							UNION ALL
SELECT								'TECH_COMBUSTION','FLAVOR_PRODUCTION',9							UNION ALL
SELECT								'TECH_COMBUSTION','FLAVOR_TILE_IMPROVEMENT',2							UNION ALL
SELECT								'TECH_COMBUSTION','FLAVOR_MILITARY_TRAINING',6							UNION ALL
SELECT								'TECH_CARRIAGES','FLAVOR_HAPPINESS',4							UNION ALL
SELECT								'TECH_CARRIAGES','FLAVOR_CULTURE',2							UNION ALL
SELECT								'TECH_CARRIAGES','FLAVOR_OFFENSE',1							UNION ALL
SELECT								'TECH_CARRIAGES','FLAVOR_RANGED',2							UNION ALL
SELECT								'TECH_CARRIAGES','FLAVOR_MOBILE',4							UNION ALL
SELECT								'TECH_CARRIAGES','FLAVOR_DEFENSE',3							UNION ALL
SELECT								'TECH_BRONZE_WORKING','FLAVOR_OFFENSE',1							UNION ALL
SELECT								'TECH_BRONZE_WORKING','FLAVOR_GOLD',2							UNION ALL
SELECT								'TECH_BRONZE_WORKING','FLAVOR_CULTURE',2							UNION ALL
SELECT								'TECH_ARCHERY','FLAVOR_OFFENSE',1							UNION ALL
SELECT								'TECH_MILITARY_TRAINING','FLAVOR_OFFENSE',3							UNION ALL
SELECT								'TECH_MILITARY_TRAINING','FLAVOR_DEFENSE',2							UNION ALL
SELECT								'TECH_MILITARY_TRAINING','FLAVOR_MILITARY_TRAINING',10							UNION ALL
SELECT								'TECH_SHIPBUILDING','FLAVOR_NAVAL',12							UNION ALL
SELECT								'TECH_HORSEBACK_RIDING','FLAVOR_PRODUCTION',2							UNION ALL
SELECT								'TECH_HORSEBACK_RIDING','FLAVOR_TILE_IMPROVEMENT',3							UNION ALL
SELECT								'TECH_HORSEBACK_RIDING','FLAVOR_MILITARY_TRAINING',2							UNION ALL
SELECT								'TECH_METAL_CASTING','FLAVOR_DEFENSE',9							UNION ALL
SELECT								'TECH_METAL_CASTING','FLAVOR_TILE_IMPROVEMENT',2							UNION ALL
SELECT								'TECH_METAL_CASTING','FLAVOR_RANGED',7							UNION ALL
SELECT								'TECH_RUDDER','FLAVOR_NAVAL',12							UNION ALL
SELECT								'TECH_FEUDALISM','FLAVOR_DEFENSE',8							UNION ALL
SELECT								'TECH_FEUDALISM','FLAVOR_WONDER',6							UNION ALL
SELECT								'TECH_FEUDALISM','FLAVOR_GROWTH',1							UNION ALL
SELECT								'TECH_FEUDALISM','FLAVOR_CITY_DEFENSE',2							UNION ALL
SELECT								'TECH_FEUDALISM','FLAVOR_MILITARY_TRAINING',3							UNION ALL
SELECT								'TECH_METALLURGY','FLAVOR_WONDER',3							UNION ALL
SELECT								'TECH_SIEGE_ENGINES','FLAVOR_RANGED',7							UNION ALL
SELECT								'TECH_SIEGE_ENGINES','FLAVOR_OFFENSE',9							UNION ALL
SELECT								'TECH_SIEGE_ENGINES','FLAVOR_DEFENSE',2							UNION ALL
SELECT								'TECH_NAVIGATION','FLAVOR_NAVAL_TILE_IMPROVEMENT',5							UNION ALL
SELECT								'TECH_NAVIGATION','FLAVOR_NAVAL_GROWTH',5							UNION ALL
SELECT								'TECH_GUNPOWDER','FLAVOR_OFFENSE',7							UNION ALL
SELECT								'TECH_GUNPOWDER','FLAVOR_TILE_IMPROVEMENT',1							UNION ALL
SELECT								'TECH_MILITARY_TRADITION','FLAVOR_MOBILE',8							UNION ALL
SELECT								'TECH_MILITARY_TRADITION','FLAVOR_OFFENSE',8							UNION ALL
SELECT								'TECH_MILITARY_TRADITION','FLAVOR_MILITARY_TRAINING',5							UNION ALL
SELECT								'TECH_CHEMISTRY','FLAVOR_OFFENSE',11							UNION ALL
SELECT								'TECH_CHEMISTRY','FLAVOR_DEFENSE',3							UNION ALL
SELECT								'TECH_RIFLING','FLAVOR_RANGED',5							UNION ALL
SELECT								'TECH_NAVAL_ARMOR','FLAVOR_NAVAL',15							UNION ALL
SELECT								'TECH_SHELLS','FLAVOR_RANGED',23							UNION ALL
SELECT								'TECH_SHELLS','FLAVOR_OFFENSE',11							UNION ALL
SELECT								'TECH_SHELLS','FLAVOR_DEFENSE',6							UNION ALL
SELECT								'TECH_MILITARY_SCIENCE','FLAVOR_DEFENSE',8							UNION ALL
SELECT								'TECH_TORPEDOES','FLAVOR_NAVAL',15							UNION ALL
SELECT								'TECH_TORPEDOES','FLAVOR_NAVAL_RECON',8							UNION ALL
SELECT								'TECH_FLIGHT','FLAVOR_OFFENSE',8							UNION ALL
SELECT								'TECH_FLIGHT','FLAVOR_DEFENSE',5							UNION ALL
SELECT								'TECH_FLIGHT','FLAVOR_MILITARY_TRAINING',6							UNION ALL
SELECT								'TECH_FLIGHT','FLAVOR_PRODUCTION',2							UNION ALL
SELECT								'TECH_TRACKED_VEHICLES','FLAVOR_OFFENSE',15							UNION ALL
SELECT								'TECH_TRACKED_VEHICLES','FLAVOR_DEFENSE',5							UNION ALL
SELECT								'TECH_TRACKED_VEHICLES','FLAVOR_MOBILE',7							UNION ALL
SELECT								'TECH_SUBMERSIBLES','FLAVOR_NAVAL',15							UNION ALL
SELECT								'TECH_SUBMERSIBLES','FLAVOR_NAVAL_RECON',7							UNION ALL
SELECT								'TECH_BIG_GUNS_DOCTRINE','FLAVOR_NAVAL',25							UNION ALL
SELECT								'TECH_RADAR','FLAVOR_DEFENSE',8							UNION ALL
SELECT								'TECH_BLITZKRIEG','FLAVOR_MOBILE',35							UNION ALL
SELECT								'TECH_BLITZKRIEG','FLAVOR_OFFENSE',45							UNION ALL
SELECT								'TECH_POTTERY','FLAVOR_WONDER',2							UNION ALL
SELECT								'TECH_POTTERY','FLAVOR_INFRASTRUCTURE',1							UNION ALL
SELECT								'TECH_ORAL_TRADITION','FLAVOR_SCIENCE',4							UNION ALL
SELECT								'TECH_ORAL_TRADITION','FLAVOR_GOLD',1							UNION ALL
SELECT								'TECH_ORAL_TRADITION','FLAVOR_MILITARY_TRAINING',1							UNION ALL
SELECT								'TECH_ORAL_TRADITION','FLAVOR_CITY_DEFENSE',2							UNION ALL
SELECT								'TECH_ORAL_TRADITION','FLAVOR_INFRASTRUCTURE',2							UNION ALL
SELECT								'TECH_THE_WHEEL','FLAVOR_EXPANSION',4							UNION ALL
SELECT								'TECH_THE_WHEEL','FLAVOR_PRODUCTION',1							UNION ALL
SELECT								'TECH_MATHEMATICS','FLAVOR_PRODUCTION',6							UNION ALL
SELECT								'TECH_MATHEMATICS','FLAVOR_CULTURE',4							UNION ALL
SELECT								'TECH_MATHEMATICS','FLAVOR_INFRASTRUCTURE',2							UNION ALL
SELECT								'TECH_MATHEMATICS','FLAVOR_TILE_IMPROVEMENT',2							UNION ALL
SELECT								'TECH_OPTICS','FLAVOR_NAVAL_TILE_IMPROVEMENT',2							UNION ALL
SELECT								'TECH_OPTICS','FLAVOR_WONDER',3							UNION ALL
SELECT								'TECH_COMPASS','FLAVOR_NAVAL_TILE_IMPROVEMENT',5							UNION ALL
SELECT								'TECH_PHYSICS','FLAVOR_WONDER',3							UNION ALL
SELECT								'TECH_PHYSICS','FLAVOR_SCIENCE',4							UNION ALL
SELECT								'TECH_ALGEBRA','FLAVOR_WONDER',3							UNION ALL
SELECT								'TECH_ALGEBRA','FLAVOR_SCIENCE',5							UNION ALL
SELECT								'TECH_ALGEBRA','FLAVOR_GREAT_PEOPLE',2							UNION ALL
SELECT								'TECH_EDUCATION','FLAVOR_GREAT_PEOPLE',3							UNION ALL
SELECT								'TECH_EDUCATION','FLAVOR_INFRASTRUCTURE',3							UNION ALL
SELECT								'TECH_ASTRONOMY','FLAVOR_WONDER',3							UNION ALL
SELECT								'TECH_ASTRONOMY','FLAVOR_INFRASTRUCTURE',3							UNION ALL
SELECT								'TECH_PRINTING_PRESS','FLAVOR_GREAT_PEOPLE',4							UNION ALL
SELECT								'TECH_PRINTING_PRESS','FLAVOR_CULTURE',4							UNION ALL
SELECT								'TECH_PRINTING_PRESS','FLAVOR_SCIENCE',4							UNION ALL
SELECT								'TECH_CALCULUS','FLAVOR_WONDER',5							UNION ALL
SELECT								'TECH_CALCULUS','FLAVOR_SCIENCE',10							UNION ALL
SELECT								'TECH_SCIENTIFIC_THEORY','FLAVOR_TILE_IMPROVEMENT',3							UNION ALL
SELECT								'TECH_BIOLOGY','FLAVOR_SCIENCE',4							UNION ALL
SELECT								'TECH_BIOLOGY','FLAVOR_GREAT_PEOPLE',2							UNION ALL
SELECT								'TECH_BIOLOGY','FLAVOR_HAPPINESS',3							UNION ALL
SELECT								'TECH_AGRICULTURAL_SCIENCES','FLAVOR_GROWTH',20							UNION ALL
SELECT								'TECH_AGRICULTURAL_SCIENCES','FLAVOR_PRODUCTION',5							UNION ALL
SELECT								'TECH_AGRICULTURAL_SCIENCES','FLAVOR_GOLD',5							UNION ALL
SELECT								'TECH_ELECTRICITY','FLAVOR_WONDER',6							UNION ALL
SELECT								'TECH_ELECTRICITY','FLAVOR_PRODUCTION',8							UNION ALL
SELECT								'TECH_ELECTRICITY','FLAVOR_SCIENCE',3							UNION ALL
SELECT								'TECH_ELECTRICITY','FLAVOR_INFRASTRUCTURE',1							UNION ALL
SELECT								'TECH_ELECTRICITY','FLAVOR_TILE_IMPROVEMENT',2							UNION ALL
SELECT								'TECH_PENICILIN','FLAVOR_MILITARY_TRAINING',2							UNION ALL
SELECT								'TECH_PENICILIN','FLAVOR_OFFENSE',3							UNION ALL
SELECT								'TECH_PENICILIN','FLAVOR_DEFENSE',4							UNION ALL
SELECT								'TECH_REFINING','FLAVOR_CITY_DEFENSE',7							UNION ALL
SELECT								'TECH_REFINING','FLAVOR_MILITARY_TRAINING',3							UNION ALL
SELECT								'TECH_REFINING','FLAVOR_NAVAL',7							UNION ALL
SELECT								'TECH_REFINING','FLAVOR_TILE_IMPROVEMENT',6							UNION ALL
SELECT								'TECH_REFINING','FLAVOR_PRODUCTION',4							UNION ALL
SELECT								'TECH_REFINING','FLAVOR_GOLD',8							UNION ALL
SELECT								'TECH_TELEPHONE','FLAVOR_GOLD',6							UNION ALL
SELECT								'TECH_TELEPHONE','FLAVOR_WONDER',3							UNION ALL
SELECT								'TECH_TELEPHONE','FLAVOR_SCIENCE',3							UNION ALL
SELECT								'TECH_TELEPHONE','FLAVOR_TILE_IMPROVEMENT',1							UNION ALL
SELECT								'TECH_PLASTIC','FLAVOR_HAPPINESS',7							UNION ALL
SELECT								'TECH_PHARMACEUTICALS','FLAVOR_PRODUCTION',4							UNION ALL
SELECT								'TECH_PHARMACEUTICALS','FLAVOR_HAPPINESS',12							UNION ALL
SELECT								'TECH_PHARMACEUTICALS','FLAVOR_WONDER',4							UNION ALL
SELECT								'TECH_MYSTICISM','FLAVOR_RELIGION',12							UNION ALL
SELECT								'TECH_MYSTICISM','FLAVOR_HAPPINESS',2							UNION ALL
SELECT								'TECH_MYSTICISM','FLAVOR_WONDER',1							UNION ALL
SELECT								'TECH_CEREMONIAL_BURIAL','FLAVOR_CULTURE',15							UNION ALL
SELECT								'TECH_CALENDAR','FLAVOR_CULTURE',10							UNION ALL
SELECT								'TECH_POLYTHEISM','FLAVOR_CULTURE',11							UNION ALL
SELECT								'TECH_POLYTHEISM','FLAVOR_WONDER',5							UNION ALL
SELECT								'TECH_MEDITATION','FLAVOR_WONDER',6							UNION ALL
SELECT								'TECH_MEDITATION','FLAVOR_CULTURE',9							UNION ALL
SELECT								'TECH_MEDITATION','FLAVOR_SCIENCE',4							UNION ALL
SELECT								'TECH_SPORTS','FLAVOR_WONDER',3							UNION ALL
SELECT								'TECH_SPORTS','FLAVOR_HAPPINESS',19							UNION ALL
SELECT								'TECH_MONOTHEISM','FLAVOR_WONDER',3							UNION ALL
SELECT								'TECH_MONOTHEISM','FLAVOR_CULTURE',6							UNION ALL
SELECT								'TECH_MONOTHEISM','FLAVOR_HAPPINESS',10							UNION ALL
SELECT								'TECH_PRIESTHOOD','FLAVOR_HAPPINESS',3							UNION ALL
SELECT								'TECH_PRIESTHOOD','FLAVOR_RELIGION',10							UNION ALL
SELECT								'TECH_PRIESTHOOD','FLAVOR_GOLD',2							UNION ALL
SELECT								'TECH_HERBAL_SCIENCE','FLAVOR_SCIENCE',8							UNION ALL
SELECT								'TECH_HERBAL_SCIENCE','FLAVOR_GOLD',2							UNION ALL
SELECT								'TECH_PHILOSOPHY','FLAVOR_CULTURE',5							UNION ALL
SELECT								'TECH_CODE_OF_LAWS','FLAVOR_HAPPINESS',20							UNION ALL
SELECT								'TECH_CODE_OF_LAWS','FLAVOR_EXPANSION',3							UNION ALL
SELECT								'TECH_CODE_OF_LAWS','FLAVOR_OFFENSE',3							UNION ALL
SELECT								'TECH_CODE_OF_LAWS','FLAVOR_GROWTH',3							UNION ALL
SELECT								'TECH_CODE_OF_LAWS','FLAVOR_WONDER',3							UNION ALL
SELECT								'TECH_POETRY','FLAVOR_OFFENSE',7							UNION ALL
SELECT								'TECH_POETRY','FLAVOR_WONDER',3							UNION ALL
SELECT								'TECH_POETRY','FLAVOR_CULTURE',8							UNION ALL
SELECT								'TECH_THEOLOGY','FLAVOR_HAPPINESS',9							UNION ALL
SELECT								'TECH_LITERATURE','FLAVOR_CULTURE',15							UNION ALL
SELECT								'TECH_LITERATURE','FLAVOR_WONDER',3							UNION ALL
SELECT								'TECH_BUREAUCRACY','FLAVOR_GOLD',15							UNION ALL
SELECT								'TECH_FUNDAMENTALISM','FLAVOR_WONDER',9							UNION ALL
SELECT								'TECH_FUNDAMENTALISM','FLAVOR_GOLD',2							UNION ALL
SELECT								'TECH_FUNDAMENTALISM','FLAVOR_HAPPINESS',1							UNION ALL
SELECT								'TECH_FUNDAMENTALISM','FLAVOR_CULTURE',6							UNION ALL
SELECT								'TECH_ACOUSTICS','FLAVOR_HAPPINESS',15							UNION ALL
SELECT								'TECH_CIVIL_SERVICE','FLAVOR_HAPPINESS',6							UNION ALL
SELECT								'TECH_CIVIL_SERVICE','FLAVOR_CULTURE',4							UNION ALL
SELECT								'TECH_ENLIGHTENMENT','FLAVOR_CULTURE',4							UNION ALL
SELECT								'TECH_ENLIGHTENMENT','FLAVOR_GREAT_PEOPLE',8							UNION ALL
SELECT								'TECH_ENLIGHTENMENT','FLAVOR_CULTURE',3							UNION ALL
SELECT								'TECH_ENLIGHTENMENT','FLAVOR_WONDER',2							UNION ALL
SELECT								'TECH_EVANGELISM','FLAVOR_HAPPINESS',14							UNION ALL
SELECT								'TECH_EVANGELISM','FLAVOR_CULTURE',6							UNION ALL
SELECT								'TECH_CONSTITUTION','FLAVOR_CULTURE',5							UNION ALL
SELECT								'TECH_CONSTITUTION','FLAVOR_HAPPINESS',16							UNION ALL
SELECT								'TECH_CONSTITUTION','FLAVOR_PRODUCTION',5							UNION ALL
SELECT								'TECH_NATIONALISM','FLAVOR_HAPPINESS',4							UNION ALL
SELECT								'TECH_NATIONALISM','FLAVOR_TILE_IMPROVEMENT',3							UNION ALL
SELECT								'TECH_NATIONALISM','FLAVOR_CULTURE',3							UNION ALL
SELECT								'TECH_NATIONALISM','FLAVOR_SCIENCE',3							UNION ALL
SELECT								'TECH_MARXISM','FLAVOR_CULTURE',10							UNION ALL
SELECT								'TECH_MARXISM','FLAVOR_WONDER',3							UNION ALL
SELECT								'TECH_RADIO','FLAVOR_HAPPINESS',15							UNION ALL
SELECT								'TECH_RADIO','FLAVOR_CULTURE',12							UNION ALL
SELECT								'TECH_RADIO','FLAVOR_TILE_IMPROVEMENT',1							UNION ALL
SELECT								'TECH_SOCIALISM','FLAVOR_HAPPINESS',12							UNION ALL
SELECT								'TECH_SOCIALISM','FLAVOR_PRODUCTION',6							UNION ALL
SELECT								'TECH_SOCIALISM','FLAVOR_INFRASTRUCTURE',2							UNION ALL
SELECT								'TECH_ECOLOGY','FLAVOR_HAPPINESS',20;
