-- Delete Existing table
DROP TABLE IF EXISTS "Technology_PrereqTechs";
-- Create New Table
CREATE TABLE Technology_PrereqTechs ('TechType' text , 
									 'PrereqTech' text , foreign key (TechType) references Technologies(Type), foreign key (PrereqTech) references Technologies(Type));
-- Populate Table, Ancient
--Settler
INSERT INTO "Technology_PrereqTechs" VALUES('TECH_CALENDAR','TECH_AGRICULTURE');
INSERT INTO "Technology_PrereqTechs" VALUES('TECH_ANIMAL_HUSBANDRY','TECH_AGRICULTURE');
INSERT INTO "Technology_PrereqTechs" VALUES('TECH_HERDING','TECH_ANIMAL_HUSBANDRY');

INSERT INTO "Technology_PrereqTechs" VALUES('TECH_RAW_MATERIALS','TECH_MINING');
INSERT INTO "Technology_PrereqTechs" VALUES('TECH_POTTERY','TECH_CALENDAR');
INSERT INTO "Technology_PrereqTechs" VALUES('TECH_POTTERY','TECH_RAW_MATERIALS');
INSERT INTO "Technology_PrereqTechs" VALUES('TECH_MASONRY','TECH_POTTERY');

--Nomad
INSERT INTO "Technology_PrereqTechs" VALUES('TECH_SHIPBUILDING','TECH_SAILING');

INSERT INTO "Technology_PrereqTechs" VALUES('TECH_TRADING','TECH_ECONOMY_OF_SCALE');
INSERT INTO "Technology_PrereqTechs" VALUES('TECH_FERMENTATION','TECH_TRADING');

INSERT INTO "Technology_PrereqTechs" VALUES('TECH_ARCHERY','TECH_TRAPPING');
INSERT INTO "Technology_PrereqTechs" VALUES('TECH_BRONZE_WORKING','TECH_TRAPPING');

--Spirit
INSERT INTO "Technology_PrereqTechs" VALUES('TECH_CEREMONIAL_BURIAL','TECH_ORAL_TRADITION');
INSERT INTO "Technology_PrereqTechs" VALUES('TECH_GREAT_MONUMENTS','TECH_CEREMONIAL_BURIAL');

INSERT INTO "Technology_PrereqTechs" VALUES('TECH_POLYTHEISM','TECH_MYSTICISM');
INSERT INTO "Technology_PrereqTechs" VALUES('TECH_MEDITATION','TECH_POLYTHEISM');
INSERT INTO "Technology_PrereqTechs" VALUES('TECH_SPORTS','TECH_MEDITATION');
INSERT INTO "Technology_PrereqTechs" VALUES('TECH_MILITARY_TRAINING','TECH_SPORTS');

--**Links Between Ancient and Classical**
INSERT INTO "Technology_PrereqTechs" VALUES('TECH_THE_WHEEL','TECH_HERDING');
INSERT INTO "Technology_PrereqTechs" VALUES('TECH_THE_WHEEL','TECH_BRONZE_WORKING');
INSERT INTO "Technology_PrereqTechs" VALUES('TECH_CURRENCY','TECH_TRADING');
INSERT INTO "Technology_PrereqTechs" VALUES('TECH_CURRENCY','TECH_BRONZE_WORKING');

INSERT INTO "Technology_PrereqTechs" VALUES('TECH_WRITING','TECH_MEDITATION');
INSERT INTO "Technology_PrereqTechs" VALUES('TECH_WRITING','TECH_GREAT_MONUMENTS');

INSERT INTO "Technology_PrereqTechs" VALUES('TECH_CONSTRUCTION','TECH_MASONRY');
INSERT INTO "Technology_PrereqTechs" VALUES('TECH_IRON_WORKING','TECH_MILITARY_TRAINING');
INSERT INTO "Technology_PrereqTechs" VALUES('TECH_OPTICS','TECH_SHIPBUILDING');

-- Populate Table, Classical
-- Number Theory
INSERT INTO "Technology_PrereqTechs" VALUES('TECH_CARRIAGES','TECH_THE_WHEEL');
INSERT INTO "Technology_PrereqTechs" VALUES('TECH_MATHEMATICS','TECH_CARRIAGES');
INSERT INTO "Technology_PrereqTechs" VALUES('TECH_HORSEBACK_RIDING','TECH_CARRIAGES');

INSERT INTO "Technology_PrereqTechs" VALUES('TECH_CURRENCY','TECH_MATHEMATICS');
INSERT INTO "Technology_PrereqTechs" VALUES('TECH_FARMERS_MARKETS','TECH_CURRENCY');
INSERT INTO "Technology_PrereqTechs" VALUES('TECH_FISH_MARKETS','TECH_CURRENCY');
INSERT INTO "Technology_PrereqTechs" VALUES('TECH_ANIMAL_MARKETS','TECH_CURRENCY');
-- Alphabet
INSERT INTO "Technology_PrereqTechs" VALUES('TECH_PHILOSOPHY','TECH_WRITING');
INSERT INTO "Technology_PrereqTechs" VALUES('TECH_MONOTHEISM','TECH_PHILOSOPHY');
INSERT INTO "Technology_PrereqTechs" VALUES('TECH_PRIESTHOOD','TECH_PHILOSOPHY');
INSERT INTO "Technology_PrereqTechs" VALUES('TECH_CODE_OF_LAWS','TECH_PRIESTHOOD');

INSERT INTO "Technology_PrereqTechs" VALUES('TECH_POETRY','TECH_WRITING');
INSERT INTO "Technology_PrereqTechs" VALUES('TECH_HERBAL_SCIENCE','TECH_POETRY');
INSERT INTO "Technology_PrereqTechs" VALUES('TECH_APOTHECARY','TECH_HERBAL_SCIENCE');

-- Artisans
INSERT INTO "Technology_PrereqTechs" VALUES('TECH_DIVISION_OF_LABOR','TECH_CONSTRUCTION');
INSERT INTO "Technology_PrereqTechs" VALUES('TECH_STONE_MASONS','TECH_DIVISION_OF_LABOR');
INSERT INTO "Technology_PrereqTechs" VALUES('TECH_WOODWORKING','TECH_DIVISION_OF_LABOR');
INSERT INTO "Technology_PrereqTechs" VALUES('TECH_PUBLIC_WORKS','TECH_STONE_MASONS');
INSERT INTO "Technology_PrereqTechs" VALUES('TECH_PUBLIC_WORKS','TECH_WOODWORKING');
INSERT INTO "Technology_PrereqTechs" VALUES('TECH_IRON_WORKING','TECH_DIVISION_OF_LABOR');
INSERT INTO "Technology_PrereqTechs" VALUES('TECH_OPTICS','TECH_IRON_WORKING');

--**Links Between Classical and Medieval**

-- Polulate the table, Medieval Techs 
-- Exotic Goods

INSERT INTO "Technology_PrereqTechs" VALUES('TECH_LIVESTOCK_DISTRIBUTION','TECH_AGRICULTURAL_REVOLUTION');
INSERT INTO "Technology_PrereqTechs" VALUES('TECH_COFFEE_TRADE','TECH_AGRICULTURAL_REVOLUTION');
INSERT INTO "Technology_PrereqTechs" VALUES('TECH_COFFEE_TRADE','TECH_TRADE_FAIRS');

INSERT INTO "Technology_PrereqTechs" VALUES('TECH_BUREAUCRACY','TECH_TRADE_FAIRS');
INSERT INTO "Technology_PrereqTechs" VALUES('TECH_METALLURGY','TECH_TRADE_FAIRS');
INSERT INTO "Technology_PrereqTechs" VALUES('TECH_BONDS','TECH_BUREAUCRACY');
INSERT INTO "Technology_PrereqTechs" VALUES('TECH_CIVIL_SERVICE','TECH_METALLURGY');

-- Medieval University
INSERT INTO "Technology_PrereqTechs" VALUES('TECH_CHIVALRY','TECH_LITERATURE');
INSERT INTO "Technology_PrereqTechs" VALUES('TECH_FEUDALISM','TECH_CHIVALRY');
INSERT INTO "Technology_PrereqTechs" VALUES('TECH_FUNDAMENTALISM','TECH_CHIVALRY');

INSERT INTO "Technology_PrereqTechs" VALUES('TECH_ACOUSTICS','TECH_DRAMA');
INSERT INTO "Technology_PrereqTechs" VALUES('TECH_THEOLOGY','TECH_DRAMA');
INSERT INTO "Technology_PrereqTechs" VALUES('TECH_ARCHAEOLOGY','TECH_THEOLOGY');

-- Empiricism
INSERT INTO "Technology_PrereqTechs" VALUES('TECH_METAL_CASTING','TECH_ENGINEERING');
INSERT INTO "Technology_PrereqTechs" VALUES('TECH_MACHINERY','TECH_METAL_CASTING');

INSERT INTO "Technology_PrereqTechs" VALUES('TECH_RUDDER','TECH_COMPASS');
INSERT INTO "Technology_PrereqTechs" VALUES('TECH_PHYSICS','TECH_COMPASS');
INSERT INTO "Technology_PrereqTechs" VALUES('TECH_ALGEBRA','TECH_PHYSICS');
INSERT INTO "Technology_PrereqTechs" VALUES('TECH_SIEGE_ENGINES','TECH_ALGEBRA');


-- Populate the table, Renassiance Techs 
-- Homo Universalis
INSERT INTO "Technology_PrereqTechs" VALUES('TECH_BANKING','TECH_GUILDS');
INSERT INTO "Technology_PrereqTechs" VALUES('TECH_CONSTITUTION','TECH_GUILDS');
INSERT INTO "Technology_PrereqTechs" VALUES('TECH_NATIONALISM','TECH_BANKING');

INSERT INTO "Technology_PrereqTechs" VALUES('TECH_PRINTING_PRESS','TECH_EDUCATION');
INSERT INTO "Technology_PrereqTechs" VALUES('TECH_ARCHITECTURE','TECH_EDUCATION');
INSERT INTO "Technology_PrereqTechs" VALUES('TECH_SCIENTIFIC_THEORY','TECH_PRINTING_PRESS');

-- Geocentrism
INSERT INTO "Technology_PrereqTechs" VALUES('TECH_ENLIGHTENMENT','TECH_ASTRONOMY');
INSERT INTO "Technology_PrereqTechs" VALUES('TECH_CALCULUS','TECH_ASTRONOMY');
INSERT INTO "Technology_PrereqTechs" VALUES('TECH_EVANGELISM','TECH_ENLIGHTENMENT');
INSERT INTO "Technology_PrereqTechs" VALUES('TECH_NAVIGATION','TECH_CALCULUS');
INSERT INTO "Technology_PrereqTechs" VALUES('TECH_OCEAN_PIONEERING','TECH_NAVIGATION');
INSERT INTO "Technology_PrereqTechs" VALUES('TECH_INTERNATIONAL_TRADE','TECH_OCEAN_PIONEERING');

-- Alchemy
INSERT INTO "Technology_PrereqTechs" VALUES('TECH_BLAST_FURNACE','TECH_STEEL');
INSERT INTO "Technology_PrereqTechs" VALUES('TECH_MILITARY_TRADITION','TECH_BLAST_FURNACE');

INSERT INTO "Technology_PrereqTechs" VALUES('TECH_CHEMISTRY','TECH_GUNPOWDER');
INSERT INTO "Technology_PrereqTechs" VALUES('TECH_FERTILIZER','TECH_CHEMISTRY');
INSERT INTO "Technology_PrereqTechs" VALUES('TECH_RIFLING','TECH_CHEMISTRY');


-- Populate the table, Industrial Techs 
-- INDUSTRIAL REVOLUTION
INSERT INTO "Technology_PrereqTechs" VALUES('TECH_STEAM_POWER','TECH_INDUSTRIALIZATION');
INSERT INTO "Technology_PrereqTechs" VALUES('TECH_DYNAMITE','TECH_STEAM_POWER');
INSERT INTO "Technology_PrereqTechs" VALUES('TECH_NAVAL_ARMOR','TECH_STEAM_POWER');
INSERT INTO "Technology_PrereqTechs" VALUES('TECH_RAILROAD','TECH_DYNAMITE');

INSERT INTO "Technology_PrereqTechs" VALUES('TECH_REPLACEABLE_PARTS','TECH_INDUSTRIALIZATION');
INSERT INTO "Technology_PrereqTechs" VALUES('TECH_COMBUSTION','TECH_REPLACEABLE_PARTS');
INSERT INTO "Technology_PrereqTechs" VALUES('TECH_COMBINED_ARMS','TECH_COMBUSTION');
INSERT INTO "Technology_PrereqTechs" VALUES('TECH_INDUSTRIAL_PROCESSES','TECH_COMBUSTION');

INSERT INTO "Technology_PrereqTechs" VALUES('TECH_REFINING','TECH_INDUSTRIALIZATION');
INSERT INTO "Technology_PrereqTechs" VALUES('TECH_PLASTIC','TECH_REFINING');

INSERT INTO "Technology_PrereqTechs" VALUES('TECH_ECONOMICS','TECH_INDUSTRIALIZATION');
INSERT INTO "Technology_PrereqTechs" VALUES('TECH_CORPORATIONS','TECH_ECONOMICS');
INSERT INTO "Technology_PrereqTechs" VALUES('TECH_MARXISM','TECH_ECONOMICS');
INSERT INTO "Technology_PrereqTechs" VALUES('TECH_SOCIALISM','TECH_ECONOMICS');

-- Science
INSERT INTO "Technology_PrereqTechs" VALUES('TECH_PENICILIN','TECH_BIOLOGY');
INSERT INTO "Technology_PrereqTechs" VALUES('TECH_AGRICULTURAL_SCIENCES','TECH_BIOLOGY');
INSERT INTO "Technology_PrereqTechs" VALUES('TECH_PHARMACEUTICALS','TECH_PENICILIN');
INSERT INTO "Technology_PrereqTechs" VALUES('TECH_ECOLOGY','TECH_AGRICULTURAL_SCIENCES');

INSERT INTO "Technology_PrereqTechs" VALUES('TECH_REFRIGERATION','TECH_ELECTRICITY');
INSERT INTO "Technology_PrereqTechs" VALUES('TECH_RADIO','TECH_ELECTRICITY');
INSERT INTO "Technology_PrereqTechs" VALUES('TECH_RADAR','TECH_RADIO');
INSERT INTO "Technology_PrereqTechs" VALUES('TECH_TELECOM','TECH_RADIO');
INSERT INTO "Technology_PrereqTechs" VALUES('TECH_TELEPHONE','TECH_TELECOM');

-- Social Classes - Military Research
INSERT INTO "Technology_PrereqTechs" VALUES('TECH_BALLISTICS','TECH_MILITARY_SCIENCE');
INSERT INTO "Technology_PrereqTechs" VALUES('TECH_SHELLS','TECH_BALLISTICS');
INSERT INTO "Technology_PrereqTechs" VALUES('TECH_BIG_GUNS_DOCTRINE','TECH_SHELLS');
INSERT INTO "Technology_PrereqTechs" VALUES('TECH_TRACKED_VEHICLES','TECH_SHELLS');
INSERT INTO "Technology_PrereqTechs" VALUES('TECH_TORPEDOES','TECH_BIG_GUNS_DOCTRINE');
INSERT INTO "Technology_PrereqTechs" VALUES('TECH_BLITZKRIEG','TECH_TRACKED_VEHICLES');
INSERT INTO "Technology_PrereqTechs" VALUES('TECH_SUBMERSIBLES','TECH_TORPEDOES');

INSERT INTO "Technology_PrereqTechs" VALUES('TECH_FLIGHT','TECH_MILITARY_SCIENCE');


-- Populate the table, Modern Techs 
-- ELECTRICAL PHENOMENA
INSERT INTO "Technology_PrereqTechs" VALUES('TECH_COMPUTERS','TECH_ELECTRONICS');
INSERT INTO "Technology_PrereqTechs" VALUES('TECH_ROBOTICS','TECH_COMPUTERS');
INSERT INTO "Technology_PrereqTechs" VALUES('TECH_LASERS','TECH_COMPUTERS');
INSERT INTO "Technology_PrereqTechs" VALUES('TECH_SOLAR_POWER','TECH_LASERS');

INSERT INTO "Technology_PrereqTechs" VALUES('TECH_MOBILE_PHONES','TECH_GLOBALIZATION');
INSERT INTO "Technology_PrereqTechs" VALUES('TECH_INTERNET','TECH_GLOBALIZATION');
INSERT INTO "Technology_PrereqTechs" VALUES('TECH_INTERNET','TECH_COMPUTERS');
INSERT INTO "Technology_PrereqTechs" VALUES('TECH_TELEVANGELISM','TECH_MOBILE_PHONES');
INSERT INTO "Technology_PrereqTechs" VALUES('TECH_CONSUMERISM','TECH_INTERNET');

-- MOLECULES
INSERT INTO "Technology_PrereqTechs" VALUES('TECH_NUCLEAR_FISSION','TECH_ATOMIC_THEORY');
INSERT INTO "Technology_PrereqTechs" VALUES('TECH_PARTICLE_PHYSICS','TECH_NUCLEAR_FISSION');
INSERT INTO "Technology_PrereqTechs" VALUES('TECH_SUPERCONDUCTORS','TECH_NUCLEAR_FISSION');

INSERT INTO "Technology_PrereqTechs" VALUES('TECH_MOBILE_TACTICS','TECH_STEALTH');
INSERT INTO "Technology_PrereqTechs" VALUES('TECH_COMPOSITE_ARMOR','TECH_MOBILE_TACTICS');
INSERT INTO "Technology_PrereqTechs" VALUES('TECH_COMBINED_ARMS_DOCTRINE','TECH_COMPOSITE_ARMOR');

INSERT INTO "Technology_PrereqTechs" VALUES('TECH_GENETICS','TECH_VACCINES');
INSERT INTO "Technology_PrereqTechs" VALUES('TECH_BIOTECH_INDUSTRY','TECH_GENETICS');
INSERT INTO "Technology_PrereqTechs" VALUES('TECH_CONSERVATIONISM','TECH_GENETICS');
INSERT INTO "Technology_PrereqTechs" VALUES('TECH_GENETIC_ENGINEERING','TECH_BIOTECH_INDUSTRY');

-- AERODYNAMICS
INSERT INTO "Technology_PrereqTechs" VALUES('TECH_ADVANCED_BALLISTICS','TECH_ROCKETRY');
INSERT INTO "Technology_PrereqTechs" VALUES('TECH_SATELLITES','TECH_ADVANCED_BALLISTICS');
INSERT INTO "Technology_PrereqTechs" VALUES('TECH_ADVANCED_FLIGHT','TECH_ADVANCED_BALLISTICS');
INSERT INTO "Technology_PrereqTechs" VALUES('TECH_CRUISE_MISSILES','TECH_ADVANCED_BALLISTICS');
INSERT INTO "Technology_PrereqTechs" VALUES('TECH_MANNED_SPACEFLIGHT','TECH_SATELLITES');
INSERT INTO "Technology_PrereqTechs" VALUES('TECH_MANNED_SPACEFLIGHT','TECH_EXTREME_SPORTS');
INSERT INTO "Technology_PrereqTechs" VALUES('TECH_UNMANNED_AIRCRAFT','TECH_ADVANCED_FLIGHT');

INSERT INTO "Technology_PrereqTechs" VALUES('TECH_EXTREME_SPORTS','TECH_MEGA_ENGINEERING');


-- Populate the table, Digital Techs 
-- DIGITAL REVOLUTION
INSERT INTO "Technology_PrereqTechs" VALUES('TECH_OPTICAL_COMPUTING','TECH_VIRTUALIZATION');
INSERT INTO "Technology_PrereqTechs" VALUES('TECH_QUANTUM_COMPUTERS','TECH_OPTICAL_COMPUTING');
INSERT INTO "Technology_PrereqTechs" VALUES('TECH_ARTIFICIAL_INTELLIGENCE','TECH_QUANTUM_COMPUTERS');
INSERT INTO "Technology_PrereqTechs" VALUES('TECH_SOCIAL_NETWORKS','TECH_QUANTUM_COMPUTERS');

-- HUMAN AUGMENTATION
INSERT INTO "Technology_PrereqTechs" VALUES('TECH_ROBOTIC_SURGERY','TECH_FUNCTIONAL_MRI');
INSERT INTO "Technology_PrereqTechs" VALUES('TECH_CLONING','TECH_FUNCTIONAL_MRI');
INSERT INTO "Technology_PrereqTechs" VALUES('TECH_EXOSKELETONS','TECH_ROBOTIC_SURGERY');
INSERT INTO "Technology_PrereqTechs" VALUES('TECH_GENETIC_SYNTHESIS','TECH_CLONING');
INSERT INTO "Technology_PrereqTechs" VALUES('TECH_BIOCOMPUTER_INTERFACE','TECH_EXOSKELETONS');
INSERT INTO "Technology_PrereqTechs" VALUES('TECH_BIOCOMPUTER_INTERFACE','TECH_GENETIC_SYNTHESIS');

-- ADVANCED ASSEMBLY
INSERT INTO "Technology_PrereqTechs" VALUES('TECH_SCRAMJET_ENGINES','TECH_SUPER_BATTERIES');
INSERT INTO "Technology_PrereqTechs" VALUES('TECH_HYBRID_SCRAMJETS','TECH_SCRAMJET_ENGINES');
INSERT INTO "Technology_PrereqTechs" VALUES('TECH_REACTOR_MINIATURIZATION','TECH_SCRAMJET_ENGINES');
INSERT INTO "Technology_PrereqTechs" VALUES('TECH_EXTREME_MECHANIZATION','TECH_HYBRID_SCRAMJETS');
INSERT INTO "Technology_PrereqTechs" VALUES('TECH_EXTREME_MECHANIZATION','TECH_REACTOR_MINIATURIZATION');

INSERT INTO "Technology_PrereqTechs" VALUES('TECH_DIGITAL_DEFENSE_DOCTRINE','TECH_LASER_MANUFACTURING');
INSERT INTO "Technology_PrereqTechs" VALUES('TECH_ADVANCED_MAGNETICS','TECH_LASER_MANUFACTURING');
INSERT INTO "Technology_PrereqTechs" VALUES('TECH_METAMATERIALS','TECH_ADVANCED_MAGNETICS');
INSERT INTO "Technology_PrereqTechs" VALUES('TECH_MAGNETICS_MINIATURIZATION','TECH_METAMATERIALS');
INSERT INTO "Technology_PrereqTechs" VALUES('TECH_ADVANCED_LASERS','TECH_MAGNETICS_MINIATURIZATION');
INSERT INTO "Technology_PrereqTechs" VALUES('TECH_UNIFIED_FIELD_THEORY','TECH_ADVANCED_LASERS');


-- Populate the table, Information Techs 
-- NEW LIFE
INSERT INTO "Technology_PrereqTechs" VALUES('TECH_BIOLOGICAL_NANITES','TECH_CYBERNETIC_ORGANISMS');
INSERT INTO "Technology_PrereqTechs" VALUES('TECH_AI_SURVEILLANCE','TECH_CYBERNETIC_ORGANISMS');
INSERT INTO "Technology_PrereqTechs" VALUES('TECH_BIOLOGICAL_SYNTHESIS','TECH_BIOLOGICAL_NANITES');
INSERT INTO "Technology_PrereqTechs" VALUES('TECH_AI_EVOLUTION','TECH_AI_SURVEILLANCE');
INSERT INTO "Technology_PrereqTechs" VALUES('TECH_MECHANICAL_BODY_GRAFTING','TECH_BIOLOGICAL_NANITES');
INSERT INTO "Technology_PrereqTechs" VALUES('TECH_NEURAL_REPROGRAMMING','TECH_BIOLOGICAL_SYNTHESIS');
INSERT INTO "Technology_PrereqTechs" VALUES('TECH_SENTIENT_ROBOTS','TECH_NEURAL_REPROGRAMMING');
INSERT INTO "Technology_PrereqTechs" VALUES('TECH_SENTIENT_ROBOTS','TECH_AI_EVOLUTION');

-- ATOM MANIPULATION
INSERT INTO "Technology_PrereqTechs" VALUES('TECH_NANOTECHNOLOGY','TECH_NUCLEAR_FUSION');
INSERT INTO "Technology_PrereqTechs" VALUES('TECH_NANO_MASS_PRODUCTION','TECH_NANOTECHNOLOGY');
INSERT INTO "Technology_PrereqTechs" VALUES('TECH_EXTREME_ENGINEERING','TECH_NANOTECHNOLOGY');
INSERT INTO "Technology_PrereqTechs" VALUES('TECH_UNDERWATER_HABITATION','TECH_EXTREME_ENGINEERING');

INSERT INTO "Technology_PrereqTechs" VALUES('TECH_PARTICLE_BEAMS','TECH_NUCLEAR_FUSION');
INSERT INTO "Technology_PrereqTechs" VALUES('TECH_FREE_SPACE_SATURATION','TECH_PARTICLE_BEAMS');
INSERT INTO "Technology_PrereqTechs" VALUES('TECH_SMART_MATERIALS','TECH_FREE_SPACE_SATURATION');

-- FRINGE SCIENCE


INSERT INTO "Technology_PrereqTechs" VALUES('TECH_2D_ENERGY_FIELDS','TECH_SPACE_WEAPONIZATION');
INSERT INTO "Technology_PrereqTechs" VALUES('TECH_WARP_FIELD_THEORY','TECH_SPACE_WEAPONIZATION');
INSERT INTO "Technology_PrereqTechs" VALUES('TECH_WORMHOLE_DETECTION','TECH_WARP_FIELD_THEORY');

INSERT INTO "Technology_PrereqTechs" VALUES('TECH_LEVITATION_MOTORS','TECH_ULTRA_PRESSURE_MACHINERY');

INSERT INTO "Technology_PrereqTechs" VALUES('TECH_SUBLIMINAL_MIND_CONTROL','TECH_VIRTUAL_REALITY');
INSERT INTO "Technology_PrereqTechs" VALUES('TECH_MIND_MELDING','TECH_SUBLIMINAL_MIND_CONTROL');

INSERT INTO "Technology_PrereqTechs" VALUES('TECH_FUTURE_TECH','TECH_ARCOLOGIES');
INSERT INTO "Technology_PrereqTechs" VALUES('TECH_FUTURE_TECH','TECH_WORMHOLE_DETECTION');
INSERT INTO "Technology_PrereqTechs" VALUES('TECH_FUTURE_TECH','TECH_LEVITATION_MOTORS');
INSERT INTO "Technology_PrereqTechs" VALUES('TECH_FUTURE_TECH','TECH_MIND_MELDING');






