ALTER TABLE Units ADD COLUMN 'PreReqPolicy' TEXT DEFAULT NULL;
ALTER TABLE Buildings ADD COLUMN 'PreReqPolicy' TEXT DEFAULT NULL;
ALTER TABLE Buildings ADD COLUMN 'LuaTurnBuildable' TEXT DEFAULT NULL;
ALTER TABLE Buildings ADD COLUMN 'TurnBuildable' INTEGER DEFAULT NULL;
--UPDATE Buildings SET LuaReq='Game.GetGameTurn() > 5' WHERE Type='BUILDING_MONUMENT';
--UPDATE Buildings SET LuaReq='RunUserTestFunction()' WHERE Type='BUILDING_MONUMENT';